@props(['config', 'preferences'])
@php $value = fn (string $key) => data_get($preferences, $key); @endphp
@if(session('status'))<div class="ws-settings-notice" role="status">{{ session('status') }}</div>@endif
@if(isset($errors) && $errors->any())<div class="ws-settings-notice is-error" role="alert">{{ $errors->first() }}</div>@endif
<div class="ws-settings-page">
    <header class="ws-settings-hero"><div><span>{{ $config['center'] }}</span><h1>System Settings</h1><p>{{ $config['description'] }}</p></div><a href="{{ route($config['account_route']) }}">My Account</a></header>
    <form method="POST" action="{{ route($config['update_route']) }}" data-workspace-settings>@csrf @method('PUT')
        <div class="ws-settings-grid">
            <section class="ws-settings-card is-wide"><header><b>⌁</b><div><h2>Notifications</h2><p>Choose which {{ $config['center'] }} updates you want to receive.</p></div></header><div class="ws-settings-list">
                @foreach($config['notifications'] as [$key,$label,$description])<label class="ws-settings-row"><span><strong>{{ $label }}</strong><small>{{ $description }}</small></span><span class="ws-settings-row-actions"><button type="button" class="ws-sound-preview" data-notification-preview="{{ $key }}" aria-label="Preview {{ $label }} sound">▶ Preview</button><span class="ws-switch"><input type="checkbox" name="{{ $key }}" value="1" @checked((bool)$value($key))><i></i></span></span></label>@endforeach
            </div></section>
            @if($config['show_ai'])<section class="ws-settings-card"><header><b>✦</b><div><h2>LIKHAE AI Assistant</h2><p>Control the optional assistant for this workspace.</p></div></header><div class="ws-settings-list"><label class="ws-settings-row"><span><strong>Show AI Assistant</strong><small>Display the floating AI chat head on {{ $config['center'] }} pages.</small></span><span class="ws-switch"><input type="checkbox" name="{{ $config['ai_key'] }}" value="1" @checked((bool)$value($config['ai_key']))><i></i></span></label><label class="ws-settings-row"><span><strong>AI Response Sound</strong><small>Play a subtle sound after the assistant replies.</small></span><span class="ws-switch"><input type="checkbox" name="{{ $config['ai_sound_key'] }}" value="1" @checked((bool)$value($config['ai_sound_key']))><i></i></span></label></div></section>@endif
            <section class="ws-settings-card"><header><b>♪</b><div><h2>Sounds</h2><p>Manage interface sound cues.</p></div></header><div class="ws-settings-list"><label class="ws-settings-row"><span><strong>Notification Sounds</strong><small>Play sounds for supported operational notifications.</small></span><span class="ws-settings-row-actions"><button type="button" class="ws-sound-preview" data-notification-preview="general_updates" aria-label="Preview notification sound">▶ Preview</button><span class="ws-switch"><input type="checkbox" name="{{ $config['sound_key'] }}" value="1" data-notification-sound-toggle @checked((bool)$value($config['sound_key']))><i></i></span></span></label></div></section>
            <section class="ws-settings-card"><header><b>◐</b><div><h2>Appearance</h2><p>Apply your preferred LIKHAE theme.</p></div></header><div class="ws-theme-options">@foreach(['light'=>['☀','Light'],'dark'=>['◐','Dark'],'system'=>['◌','System']] as $key=>[$icon,$label])<label><input type="radio" name="theme" value="{{ $key }}" @checked($value('theme')===$key)><span><em>{{ $icon }}</em>{{ $label }}</span></label>@endforeach</div></section>
            <section class="ws-settings-card"><header><b>A</b><div><h2>Language</h2><p>More languages will appear when translations are ready.</p></div></header><label class="ws-select">Display language<select name="language"><option value="en">English</option></select></label></section>
        </div><footer class="ws-settings-save"><p>Changes apply only to your {{ $config['center'] }} account.</p><button type="submit">Save Settings</button></footer>
    </form>
</div>
@push('scripts')<script>(()=>{const f=document.querySelector('[data-workspace-settings]');if(!f)return;const apply=v=>{if(v==='system')localStorage.removeItem('likhae-theme');else localStorage.setItem('likhae-theme',v);document.documentElement.classList.toggle('dark',v==='dark'||(v==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))};f.querySelectorAll('input[name="theme"]').forEach(i=>i.addEventListener('change',()=>apply(i.value)));f.addEventListener('submit',()=>{apply(f.querySelector('input[name="theme"]:checked')?.value||'system');if(f.querySelector('[data-notification-sound-toggle]')?.checked)window.likhaeEnableNotificationSounds?.()})})();</script>@endpush
