@php
$buyerProducts=[
['id'=>'wireless-headphones','slug'=>'wireless-headphones','name'=>'Premium Wireless Headphones','category'=>'Electronics','seller'=>'Metro Finds PH','location'=>'Makati City','price'=>2499,'old_price'=>2999,'discount'=>17,'rating'=>4.8,'reviews'=>128,'sold'=>250,'stock'=>18,'image'=>'/guest/products/headphones.svg'],
['id'=>'classic-backpack','slug'=>'classic-backpack','name'=>'Classic Everyday Backpack','category'=>'Bags','seller'=>'Urban Carry Co.','location'=>'Quezon City','price'=>999,'old_price'=>1299,'discount'=>23,'rating'=>4.7,'reviews'=>92,'sold'=>410,'stock'=>26,'image'=>'/guest/products/backpack.svg'],
['id'=>'running-shoes','slug'=>'running-shoes','name'=>'Lightweight Running Shoes','category'=>'Sports & Outdoors','seller'=>'Stride PH','location'=>'Pasig City','price'=>1799,'old_price'=>2199,'discount'=>18,'rating'=>4.9,'reviews'=>205,'sold'=>540,'stock'=>14,'image'=>'/guest/products/shoes.svg'],
['id'=>'smart-watch','slug'=>'smart-watch','name'=>'Everyday Smart Watch','category'=>'Electronics','seller'=>'Tech Avenue','location'=>'Taguig City','price'=>2190,'old_price'=>2690,'discount'=>19,'rating'=>4.7,'reviews'=>164,'sold'=>325,'stock'=>20,'image'=>'/guest/products/watch.svg'],
['id'=>'skincare-set','slug'=>'skincare-set','name'=>'Daily Skincare Essentials Set','category'=>'Beauty & Health','seller'=>'Glow Market','location'=>'Manila','price'=>899,'old_price'=>1099,'discount'=>18,'rating'=>4.8,'reviews'=>110,'sold'=>290,'stock'=>31,'image'=>'/guest/products/skincare.svg'],
['id'=>'mechanical-keyboard','slug'=>'mechanical-keyboard','name'=>'Compact Mechanical Keyboard','category'=>'Electronics','seller'=>'KeyHub PH','location'=>'Mandaluyong City','price'=>1899,'old_price'=>2299,'discount'=>17,'rating'=>4.9,'reviews'=>180,'sold'=>460,'stock'=>17,'image'=>'/guest/products/keyboard.svg'],
['id'=>'coffee-maker','slug'=>'coffee-maker','name'=>'Compact Home Coffee Maker','category'=>'Home & Living','seller'=>'Kitchen+ Manila','location'=>'Manila','price'=>1599,'old_price'=>1899,'discount'=>16,'rating'=>4.6,'reviews'=>84,'sold'=>170,'stock'=>11,'image'=>'/guest/products/coffee.svg'],
['id'=>'desk-lamp','slug'=>'desk-lamp','name'=>'Minimal Adjustable Desk Lamp','category'=>'Home & Living','seller'=>'Home Basics MNL','location'=>'Marikina City','price'=>749,'old_price'=>899,'discount'=>17,'rating'=>4.6,'reviews'=>71,'sold'=>180,'stock'=>22,'image'=>'/guest/products/lamp.svg'],
['id'=>'basketball','slug'=>'basketball','name'=>'Indoor / Outdoor Basketball','category'=>'Sports & Outdoors','seller'=>'Playground PH','location'=>'Cavite','price'=>699,'old_price'=>849,'discount'=>18,'rating'=>4.7,'reviews'=>89,'sold'=>201,'stock'=>34,'image'=>'/guest/products/basketball.svg'],
['id'=>'book-set','slug'=>'book-set','name'=>'Modern Reading Essentials Set','category'=>'Books & Stationery','seller'=>'Paper Trail PH','location'=>'Laguna','price'=>559,'old_price'=>699,'discount'=>20,'rating'=>4.8,'reviews'=>74,'sold'=>150,'stock'=>42,'image'=>'/guest/products/book.svg'],
['id'=>'pet-supplies','slug'=>'pet-supplies','name'=>'Everyday Pet Care Starter Set','category'=>'Pet Supplies','seller'=>'Happy Paws PH','location'=>'Quezon City','price'=>799,'old_price'=>949,'discount'=>16,'rating'=>4.9,'reviews'=>98,'sold'=>220,'stock'=>28,'image'=>'/guest/products/pet.svg'],
];
$currentSlug=$slug??request()->route('slug')??'wireless-headphones';
$product=collect($buyerProducts)->firstWhere('slug',$currentSlug)??$buyerProducts[0];
$gallery=[$product['image'],'/guest/products/camera.svg','/guest/products/watch.svg','/guest/products/backpack.svg'];
@endphp
<x-buyer.layout :title="$product['name']"><div class="b-page" data-buyer-product-detail data-product-id="{{ $product['id'] }}" data-product-name="{{ $product['name'] }}" data-product-price="{{ $product['price'] }}" data-product-image="{{ asset(ltrim($product['image'],'/')) }}" data-stock="{{ $product['stock'] }}"><div class="b-container">
<x-buyer.breadcrumbs :items="[['label'=>'Products','url'=>route('buyer.products')],['label'=>$product['category'],'url'=>route('buyer.products',['category'=>$product['category']])],['label'=>$product['name'],'url'=>null]]" />
<section class="b-product-layout"><div class="b-gallery"><div class="b-thumbnails">@foreach($gallery as $index=>$image)<button class="b-thumbnail {{ $index===0?'is-active':'' }}" type="button" data-buyer-thumbnail data-image="{{ asset(ltrim($image,'/')) }}" data-alt="{{ $product['name'] }} view {{ $index+1 }}"><img src="{{ asset(ltrim($image,'/')) }}" alt=""></button>@endforeach</div><div class="b-main-image"><img src="{{ asset(ltrim($product['image'],'/')) }}" alt="{{ $product['name'] }}" data-buyer-main-image></div></div>
<aside class="b-card b-product-panel"><x-buyer.status-badge type="danger">Best Seller</x-buyer.status-badge><h1>{{ $product['name'] }}</h1><div class="b-product-stats"><x-buyer.rating :rating="$product['rating']" :reviews="$product['reviews']" /><span>{{ $product['sold'] }} sold</span></div><x-buyer.price :price="$product['price']" :old-price="$product['old_price']" :discount="$product['discount']" /><div class="b-stock">In stock · {{ $product['stock'] }} available</div>
<div class="b-option-group" data-option-group><strong>Color</strong><div class="b-options"><button class="b-option is-selected" data-option>Black</button><button class="b-option" data-option>White</button><button class="b-option" data-option>Blue</button><button class="b-option" data-option disabled>Beige</button></div></div><div class="b-option-group" data-option-group><strong>Size / Type</strong><div class="b-options"><button class="b-option is-selected" data-option>Standard</button><button class="b-option" data-option>Premium</button></div></div><div class="b-option-group"><strong>Quantity</strong><div class="b-qty"><button data-quantity-minus>−</button><input value="1" readonly data-product-quantity><button data-quantity-plus>+</button></div></div>
<div class="b-product-actions"><button class="b-btn b-btn-secondary" data-buyer-add-cart>Add to Cart</button><button class="b-btn b-btn-primary" data-buyer-buy-now>Buy Now</button></div><div class="b-secondary-actions"><button class="b-btn b-btn-ghost" data-buyer-wishlist>♡ Add to Wishlist</button><a class="b-btn b-btn-ghost" href="{{ route('buyer.messages') }}">Message Seller</a></div></aside></section>
<div class="b-tabs"><button class="b-tab is-active" data-product-tab="description">Description</button><button class="b-tab" data-product-tab="specifications">Specifications</button><button class="b-tab" data-product-tab="reviews">Reviews</button><button class="b-tab" data-product-tab="shipping">Shipping & Returns</button></div>
<div class="b-tab-panel is-active" data-product-panel="description"><h2>Designed for everyday use</h2><p class="b-muted">Clear product information, practical performance, and a modern marketplace presentation.</p></div>
<div class="b-tab-panel" data-product-panel="specifications"><div class="b-spec-table">@foreach(['Brand'=>'LIKHAE Select','Category'=>$product['category'],'Warranty'=>'Seller warranty where applicable','Seller Location'=>$product['location'],'Condition'=>'New'] as $label=>$value)<div class="b-spec-row"><span>{{ $label }}</span><strong>{{ $value }}</strong></div>@endforeach</div></div>
<div class="b-tab-panel" data-product-panel="reviews"><h2>{{ $product['rating'] }} out of 5</h2><p class="b-muted">Based on {{ $product['reviews'] }} verified buyer reviews.</p></div>
<div class="b-tab-panel" data-product-panel="shipping"><p class="b-muted">Standard and express shipping options are shown during checkout. Eligible orders include buyer protection.</p></div>
<x-buyer.seller-card :name="$product['seller']" :location="$product['location']" />
</div></div></x-buyer.layout>
