@php
$searchQuery=trim((string)request('q',''));
$selectedCategory=trim((string)request('category',''));
@endphp
<x-buyer.layout title="Products"><div class="b-page" data-buyer-products-page><div class="b-container">
<x-buyer.breadcrumbs :items="[['label'=>'Products','url'=>null]]" />
<div class="b-products-head"><div><h1 class="b-title">@if($searchQuery)Search results for “{{ $searchQuery }}”@elseif($selectedCategory){{ $selectedCategory }}@else Explore Products @endif</h1><p class="b-muted">{{ count($buyerProducts) }} products available across LIKHAE.</p></div><button class="b-btn b-btn-secondary b-filter-mobile-btn" type="button" data-buyer-filter-toggle>Filters</button></div>
<div class="b-catalog"><aside class="b-card b-filters" data-buyer-filter-panel><div class="b-filter-group"><strong>Find in results</strong><input class="b-input" type="search" value="{{ $searchQuery }}" placeholder="Product, seller, category..." data-buyer-product-filter-search></div><div class="b-filter-group"><strong>Category</strong><label class="b-filter-option"><input type="radio" name="buyer_category_filter" value="" data-buyer-category-filter {{ $selectedCategory===''?'checked':'' }}> All categories</label>@foreach(['Electronics','Bags','Home & Living','Beauty & Health','Sports & Outdoors','Books & Stationery','Pet Supplies'] as $category)<label class="b-filter-option"><input type="radio" name="buyer_category_filter" value="{{ $category }}" data-buyer-category-filter {{ $selectedCategory===$category?'checked':'' }}> {{ $category }}</label>@endforeach</div><div class="b-filter-group"><strong>Price Range</strong><div class="b-price-fields"><input class="b-input" placeholder="Min"><input class="b-input" placeholder="Max"></div></div><div class="b-filter-group"><strong>Rating</strong><label class="b-filter-option"><input type="checkbox"> 4★ & above</label></div><div class="b-filter-group"><strong>Availability</strong><label class="b-filter-option"><input type="checkbox"> In stock</label></div></aside>
<section class="b-catalog-main"><div class="b-catalog-toolbar"><div class="b-active-filter-row"><span class="b-filter-chip">Trusted sellers</span><span class="b-filter-chip">Philippines</span></div><select class="b-select b-sort-select" data-buyer-sort><option value="relevant">Most Relevant</option><option value="best-selling">Best Selling</option><option value="highest-rated">Highest Rated</option><option value="price-low">Price Low to High</option><option value="price-high">Price High to Low</option></select></div><div class="b-product-grid" data-buyer-product-grid>@foreach($buyerProducts as $product)<x-buyer.product-card :product="$product" />@endforeach</div></section></div>
</div></div></x-buyer.layout>
