<form id="{{ $formId }}" method="POST" action="{{ route('register.store') }}" enctype="multipart/form-data" class="registration-form mt-8 {{ $role !== 'buyer' ? 'hidden' : '' }}" data-role="{{ $role }}">
    @csrf
    <input type="hidden" name="role" value="{{ $role }}">
    <div class="form-section-heading"><span class="form-section-number">02</span><div><h2>{{ $title }}</h2><p>Fields marked <span class="text-[#d92d2f]">*</span> are required.</p></div></div>
    <div class="mt-5 grid gap-5 sm:grid-cols-2">
        @include('Registration.partials.registration-input', ['name' => 'last_name', 'label' => 'Last Name', 'required' => true])
        @include('Registration.partials.registration-input', ['name' => 'first_name', 'label' => 'First Name', 'required' => true])
        @include('Registration.partials.registration-input', ['name' => 'middle_initial', 'label' => 'Middle Initial', 'required' => false, 'maxlength' => 2])
        <div><label for="{{ $role }}_sex" class="form-label">Sex <span>*</span></label><select id="{{ $role }}_sex" name="sex" required class="form-input"><option value="">Select sex</option><option value="male">Male</option><option value="female">Female</option><option value="prefer_not_to_say">Prefer not to say</option></select></div>
        @include('Registration.partials.registration-input', ['name' => 'email', 'label' => 'E-mail', 'required' => true, 'type' => 'email'])
        @include('Registration.partials.registration-input', ['name' => 'contact_number', 'label' => 'Contact No.', 'required' => true, 'type' => 'tel'])
        <div><label for="{{ $role }}_birthday" class="form-label">Birthday <span>*</span></label><input id="{{ $role }}_birthday" name="birthday" type="date" required class="form-input birthday-input"></div>
        <div><label for="{{ $role }}_age" class="form-label">Age (Auto-generated)</label><input id="{{ $role }}_age" type="number" readonly class="form-input cursor-not-allowed bg-[#f7f4f0] age-output"></div>
    </div>
    <div class="form-subsection"><h3>Address</h3><p class="form-help">Select Province, Municipality/City, and Barangay. Enter street and house details manually.</p><div class="mt-4 grid gap-5 sm:grid-cols-2">
        <div><label for="{{ $role }}_province" class="form-label">Province <span>*</span></label><select id="{{ $role }}_province" name="province" required class="form-input province-select"><option value="">Select province</option></select></div>
        <div><label for="{{ $role }}_municipality" class="form-label">Municipality / City <span>*</span></label><select id="{{ $role }}_municipality" name="municipality" required disabled class="form-input municipality-select"><option value="">Select municipality / city</option></select></div>
        <div><label for="{{ $role }}_barangay" class="form-label">Barangay <span>*</span></label><select id="{{ $role }}_barangay" name="barangay" required disabled class="form-input barangay-select"><option value="">Select barangay</option></select></div>
        @include('Registration.partials.registration-input', ['name' => 'house_number', 'label' => 'House / Unit Number', 'required' => true])
        <div class="sm:col-span-2">@include('Registration.partials.registration-input', ['name' => 'street', 'label' => 'Street / Subdivision', 'required' => true])</div>
    </div></div>
    @if($seller ?? false)<div class="form-subsection"><h3>Business Information</h3><div class="mt-4 grid gap-5 sm:grid-cols-2">@include('Registration.partials.registration-input', ['name' => 'business_name', 'label' => 'Business Name', 'required' => true])@include('Registration.partials.registration-input', ['name' => 'line_of_business', 'label' => 'Line of Business / Category', 'required' => true])</div></div>@endif
    @if($courier ?? false)<div class="form-subsection"><h3>Vehicle & Documents</h3><div class="mt-4 grid gap-5 sm:grid-cols-2"><div><label for="vehicle_type" class="form-label">Choose Vehicle <span>*</span></label><select id="vehicle_type" name="vehicle_type" required class="form-input"><option value="">Select vehicle</option><option value="motorcycle">Motorcycle</option><option value="car">Car</option><option value="van">Van</option><option value="truck">Truck</option></select></div>@include('Registration.partials.registration-input', ['name' => 'plate_number', 'label' => 'Plate Number', 'required' => true])<div><label for="or_cr" class="form-label">Upload OR/CR <span>*</span></label><input id="or_cr" name="or_cr" type="file" accept=".jpg,.jpeg,.png,.pdf" required class="form-input"></div><div><label for="drivers_license" class="form-label">Upload ID / Driver's License <span>*</span></label><input id="drivers_license" name="drivers_license" type="file" accept=".jpg,.jpeg,.png,.pdf" required class="form-input"></div></div></div>@else<div class="form-subsection"><h3>Documents</h3><div class="mt-4 grid gap-5 sm:grid-cols-2"><div><label for="{{ $role }}_valid_id" class="form-label">Upload Valid ID <span>*</span></label><input id="{{ $role }}_valid_id" name="valid_id" type="file" accept=".jpg,.jpeg,.png,.pdf" required class="form-input"></div>@if($seller ?? false)<div><label for="business_permit" class="form-label">Upload Business Permit <span>*</span></label><input id="business_permit" name="business_permit" type="file" accept=".jpg,.jpeg,.png,.pdf" required class="form-input"></div>@endif</div></div>@endif
    <div class="form-subsection"><h3>Account Security</h3><div class="mt-4 grid gap-5 sm:grid-cols-2"><div><label for="{{ $role }}_password" class="form-label">Password <span>*</span></label><input id="{{ $role }}_password" name="password" type="password" required autocomplete="new-password" class="form-input"></div><div><label for="{{ $role }}_password_confirmation" class="form-label">Confirm Password <span>*</span></label><input id="{{ $role }}_password_confirmation" name="password_confirmation" type="password" required autocomplete="new-password" class="form-input"></div></div></div>
    <div class="mt-7 border border-[#ead8a8] bg-[#fff9e8] px-4 py-4 text-xs leading-5 text-[#7a5b0f]">After submitting your registration, please wait for the administrator's approval, which will be sent to your email.</div>
    <label class="mt-6 flex items-start gap-3 text-xs leading-5 text-[#777068]"><input type="checkbox" name="terms" value="1" required class="mt-1 h-4 w-4 accent-[#d92d2f]"><span>I confirm that the information provided is correct and agree to LIKHAE's Terms and Privacy Policy.</span></label>
    <button type="submit" class="mt-6 flex h-13 w-full items-center justify-center bg-[#d92d2f] px-5 text-sm font-bold text-white transition hover:bg-[#bd2024]">Submit {{ ucfirst($role) }} Registration <span class="ml-2">&#8594;</span></button>
</form>
