<x-buyer.layout title="Checkout"><div class="b-page" data-buyer-checkout><div class="b-container">
<div class="b-checkout-progress"><span>Cart</span><span>→</span><strong>Shipping</strong><span>→</span><span>Payment</span><span>→</span><span>Review</span></div>
<div class="b-checkout-layout"><div>
<section class="b-card b-checkout-section"><h2>Delivery Address</h2><strong>Juan Dela Cruz</strong><p class="b-muted">Blk 12 Lot 3, Mahogany Street, Brgy. San Isidro, Antipolo City, Rizal 1870</p><a class="b-btn b-btn-secondary" href="{{ route('buyer.account.addresses') }}">Change Address</a></section>
<section class="b-card b-checkout-section"><h2>Shipping Method</h2><label class="b-radio-card"><input type="radio" name="shipping_method" data-fee="60" checked><span><strong>Standard Shipping · ₱60.00</strong><small class="b-muted" style="display:block">Estimated Sep 1–3</small></span></label><label class="b-radio-card"><input type="radio" name="shipping_method" data-fee="120"><span><strong>Express Shipping · ₱120.00</strong><small class="b-muted" style="display:block">Estimated Aug 30–31</small></span></label></section>
<section class="b-card b-checkout-section"><h2>Payment Method</h2>@foreach([['cod','Cash on Delivery'],['gcash','GCash'],['maya','Maya'],['card','Credit / Debit Card'],['bank','Bank Transfer']] as $i=>[$value,$label])<label class="b-radio-card"><input type="radio" name="payment_method" value="{{ $value }}" {{ $i===0?'checked':'' }}><span><strong>{{ $label }}</strong><small class="b-muted" style="display:block">Select {{ $label }} for this order.</small></span></label>@endforeach</section>
<section class="b-card b-checkout-section"><h2>Order Items</h2><div class="b-checkout-items"><div class="b-checkout-item"><img src="{{ asset('images/buyer/products/headphones.svg') }}" alt=""><div><strong>Premium Wireless Headphones</strong><div class="b-muted" style="font-size:12px">Black · Standard · Qty 1</div></div><strong>₱2,499.00</strong></div><div class="b-checkout-item"><img src="{{ asset('images/buyer/products/backpack.svg') }}" alt=""><div><strong>Classic Everyday Backpack</strong><div class="b-muted" style="font-size:12px">Brown · Qty 1</div></div><strong>₱999.00</strong></div></div></section>
</div>
<aside class="b-card b-checkout-summary"><h2 style="margin-top:0">Order Summary</h2><div class="b-summary-row"><span>Subtotal</span><strong data-checkout-subtotal>₱0.00</strong></div><div class="b-summary-row"><span>Shipping</span><strong data-checkout-shipping>₱0.00</strong></div><div class="b-summary-row"><span>Voucher</span><strong style="color:var(--ok)" data-checkout-discount>-₱0.00</strong></div><div class="b-summary-row b-summary-total"><span>Total</span><strong data-checkout-total>₱0.00</strong></div><form action="{{ route('buyer.order.store') }}" method="POST">@csrf<button class="b-btn b-btn-primary" style="width:100%;margin-top:15px" type="submit">Place Order</button></form></aside>
</div></div></div></x-buyer.layout>
