import{$,$$,readStore,writeStore,money,toast}from"./utils.js";
const fallback=[
{id:"wireless-headphones",name:"Premium Wireless Headphones",price:2499,qty:1,stock:18,image:"/images/buyer/products/headphones.svg",options:["Black","Standard"]},
{id:"classic-backpack",name:"Classic Everyday Backpack",price:999,qty:1,stock:26,image:"/images/buyer/products/backpack.svg",options:["Brown","Standard"]}
];
export function initBuyerCart(){
 const p=$("[data-buyer-cart-page]");if(!p)return;let items=readStore("likhae_buyer_cart",[]);if(!items.length)items=fallback;const list=$("[data-buyer-cart-list]",p),discount=+p.dataset.discount||200;
 const calc=()=>{let sub=0;$$("[data-cart-item]",p).forEach(r=>{const i=+r.dataset.index;if($("[data-cart-select]",r)?.checked&&items[i])sub+=items[i].price*items[i].qty});$("[data-cart-subtotal]",p).textContent=money(sub);$("[data-cart-discount]",p).textContent="-"+money(discount);$("[data-cart-total]",p).textContent=money(Math.max(0,sub-discount))};
 const save=()=>{writeStore("likhae_buyer_cart",items);render()};
 const render=()=>{if(!items.length){list.innerHTML=`<div class="b-empty"><div class="b-empty-icon">🛒</div><h3>Your cart is empty</h3><p>Browse LIKHAE products and add something you want to buy.</p><a class="b-btn b-btn-primary" href="/buyer/products">Browse Products</a></div>`;calc();return}
 list.innerHTML=items.map((x,i)=>`<article class="b-cart-item" data-cart-item data-index="${i}"><input type="checkbox" data-cart-select checked><div class="b-cart-image"><img src="${x.image}" alt=""></div><div><strong>${x.name}</strong><div class="b-muted" style="font-size:12px;margin:5px 0">Variation: ${(x.options||["Standard"]).join(" · ")}</div><div class="b-price-current">${money(x.price)}</div><div class="b-cart-actions"><button class="b-btn b-btn-ghost" type="button" data-cart-move-wishlist>Move to Wishlist</button><button class="b-btn b-btn-danger" type="button" data-cart-remove>Remove</button></div></div><div><div class="b-qty"><button data-cart-minus>−</button><input value="${x.qty}" readonly><button data-cart-plus>+</button></div></div></article>`).join("");
 $$("[data-cart-item]",p).forEach(r=>{const i=+r.dataset.index;$("[data-cart-minus]",r).onclick=()=>{items[i].qty=Math.max(1,items[i].qty-1);save()};$("[data-cart-plus]",r).onclick=()=>{items[i].qty=Math.min(items[i].stock||99,items[i].qty+1);save()};$("[data-cart-remove]",r).onclick=()=>{items.splice(i,1);toast("Item removed.");save()};$("[data-cart-move-wishlist]",r).onclick=()=>{let w=readStore("likhae_buyer_wishlist",[]);if(!w.includes(items[i].id))w.push(items[i].id);writeStore("likhae_buyer_wishlist",w);items.splice(i,1);toast("Moved to wishlist.");save()};$("[data-cart-select]",r).onchange=calc});calc()};
 $("[data-cart-select-all]",p)?.addEventListener("change",e=>{$$("[data-cart-select]",p).forEach(x=>x.checked=e.target.checked);calc()});$("[data-cart-apply-voucher]",p)?.addEventListener("click",()=>toast($("[data-cart-voucher]",p)?.value.trim()?"Voucher applied.":"Enter a voucher code first."));render();
}
