@extends('layouts.admin')
@section('title','Admin Account')
@section('subtitle','Persisted profile, security, and notification preferences.')
@section('active','account')
@section('content')
<div style="display:grid;gap:16px">@if(session('success'))<div class="ad-card ad-card-body">{{ session('success') }}</div>@endif
<div class="ad-page-head"><div><span class="ad-overline">Account</span><h2>{{ $adminUser->name }}</h2><p>{{ $adminUser->email }}</p></div></div>
<div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px"><div class="ad-card"><div class="ad-card-head"><div><h2>Profile</h2></div></div><div class="ad-card-body"><form style="display:grid;gap:12px" method="POST" action="{{ route('admin.account.update') }}">@csrf @method('PATCH')<label class="ad-field"><span>First name</span><input name="first_name" value="{{ old('first_name',$adminUser->first_name ?: str($adminUser->name)->before(' ')) }}" required></label><label class="ad-field"><span>Last name</span><input name="last_name" value="{{ old('last_name',$adminUser->last_name ?: str($adminUser->name)->after(' ')) }}" required></label><label class="ad-field"><span>Email</span><input type="email" name="email" value="{{ old('email',$adminUser->email) }}" required></label><label class="ad-field"><span>Contact number</span><input name="contact_number" value="{{ old('contact_number',$adminUser->contact_number) }}"></label><button class="ad-btn ad-btn-primary">Save profile</button></form></div></div>
<div class="ad-card"><div class="ad-card-head"><div><h2>Password</h2></div></div><div class="ad-card-body"><form style="display:grid;gap:12px" method="POST" action="{{ route('admin.account.password') }}">@csrf @method('PATCH')<label class="ad-field"><span>Current password</span><input type="password" name="current_password" required></label><label class="ad-field"><span>New password</span><input type="password" name="password" required></label><label class="ad-field"><span>Confirm new password</span><input type="password" name="password_confirmation" required></label><button class="ad-btn ad-btn-primary">Change password</button></form></div></div>
<div class="ad-card"><div class="ad-card-head"><div><h2>Notifications</h2></div></div><div class="ad-card-body"><form style="display:grid;gap:12px" method="POST" action="{{ route('admin.account.preferences') }}">@csrf @method('PATCH')@php($prefs=$preferences->notification_preferences ?? [])@foreach(['registrations'=>'Registration updates','risk'=>'Product risk alerts','finance'=>'Finance updates','messages'=>'Messages'] as $key=>$label)<label><input type="checkbox" name="{{ $key }}" value="1" @checked($prefs[$key] ?? false)> {{ $label }}</label>@endforeach<button class="ad-btn ad-btn-primary">Save preferences</button></form></div></div></div>
</div>
@endsection
