@extends('layouts.admin')
@section('title', 'Returns and Refunds')
@section('content')
<div class="ad-page-head"><div><span class="ad-overline">Cases</span><h2>Return and refund management</h2><p>Review real buyer requests linked to seller orders.</p></div></div>
<form class="ad-card ad-card-body ad-filter-bar" method="GET"><div class="ad-inline-actions"><input name="q" value="{{ request('q') }}" placeholder="Reason or order reference"><select name="status"><option value="">All statuses</option>@foreach(['requested','approved','disputed','refunded','rejected'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select><button class="ad-btn ad-btn-primary">Filter</button><a class="ad-btn ad-btn-secondary" href="{{ route('admin.complaints') }}">Reset</a></div></form>
<div class="ad-card"><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Case</th><th>Order</th><th>Buyer</th><th>Seller</th><th>Amount</th><th>Reason</th><th>Status</th><th>Decision</th></tr></thead><tbody>
@forelse($refundRecords as $return)
<tr><td><strong>RET-{{ $return->id }}</strong><small>{{ $return->created_at?->format('M d, Y H:i') }}</small></td><td>{{ $return->sellerOrder?->order?->reference }}</td><td>{{ $return->buyer?->name }}</td><td>{{ $return->sellerOrder?->seller?->name }}</td><td>₱{{ number_format(($return->sellerOrder?->subtotal_minor ?? 0) / 100, 2) }}</td><td style="white-space:normal;max-width:240px">{{ $return->reason }}@if($return->details)<small>{{ $return->details }}</small>@endif</td><td>{{ str($return->status)->headline() }}</td><td>@if(in_array($return->status, ['requested','approved','disputed'], true))<form method="POST" action="{{ route('admin.refunds.update', $return) }}">@csrf @method('PATCH')<textarea name="admin_decision" required maxlength="2000" placeholder="Decision and reason"></textarea><div class="ad-inline-actions"><button name="status" value="refunded" class="ad-btn ad-btn-primary ad-btn-sm">Refund</button><button name="status" value="rejected" class="ad-btn ad-btn-danger-soft ad-btn-sm">Reject</button></div></form>@else {{ $return->admin_decision ?: 'Resolved' }} @endif</td></tr>
@empty<tr><td colspan="8">No return requests.</td></tr>@endforelse
</tbody></table></div><div class="ad-card-body">{{ $refundRecords->links() }}</div></div>
@endsection
