@extends('layouts.admin')
@section('title','Refunds & Disputes')
@section('subtitle','Manage the refund records that actually exist in the current LIKHAE schema.')
@section('active','complaints')
@section('content')
<div style="display:grid;gap:16px">
@if(session('success'))<div class="ad-card ad-card-body">{{ session('success') }}</div>@endif
<div class="ad-page-head"><div><span class="ad-overline">Cases</span><h2>Refund management</h2><p>The project has a refunds table but no separate complaints table, so no fake complaints are shown.</p></div></div>
<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px">@foreach(['open'=>'Open/processing','pending_amount'=>'Amount at issue','resolved_week'=>'Resolved this week','total'=>'Total refunds'] as $k=>$l)<div class="ad-card ad-card-body"><small>{{ $l }}</small><h2>{{ $k==='pending_amount' ? '₱'.number_format($refundStats[$k]??0,2) : number_format($refundStats[$k]??0) }}</h2></div>@endforeach</div>
<form class="ad-card ad-card-body ad-filter-bar" method="GET"><div class="ad-inline-actions"><input name="q" value="{{ request('q') }}" placeholder="Refund or order number"><select name="status"><option value="">All statuses</option>@foreach(['open','processing','completed','rejected'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ str($s)->headline() }}</option>@endforeach</select><button class="ad-btn ad-btn-primary">Filter</button><a class="ad-btn ad-btn-secondary" href="{{ route('admin.complaints') }}">Reset</a></div></form>
<div class="ad-card"><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Refund</th><th>Order</th><th>Buyer</th><th>Seller</th><th>Amount</th><th>Reason</th><th>Status</th><th>Update</th></tr></thead><tbody>@forelse($refundRecords as $refund)<tr><td><strong>{{ $refund->refund_number }}</strong><small>{{ $refund->created_at?->format('M d, Y H:i') }}</small></td><td>{{ $refund->order?->order_number }}</td><td>{{ $refund->buyer?->name ?? $refund->order?->buyer?->name }}</td><td>{{ $refund->order?->seller?->name }}</td><td>₱{{ number_format((float)$refund->amount,2) }}</td><td style="white-space:normal;max-width:240px">{{ $refund->reason }}</td><td>{{ str($refund->status)->headline() }}</td><td><form method="POST" action="{{ route('admin.refunds.update',$refund) }}">@csrf @method('PATCH')<div class="ad-inline-actions"><select name="status">@foreach(['open','processing','completed','rejected'] as $s)<option value="{{ $s }}" @selected($refund->status===$s)>{{ str($s)->headline() }}</option>@endforeach</select><button class="ad-btn ad-btn-secondary ad-btn-sm">Save</button></div></form></td></tr>@empty<tr><td colspan="8">No refund records.</td></tr>@endforelse</tbody></table></div><div class="ad-card-body">{{ $refundRecords->links() }}</div></div>
</div>
@endsection
