@extends('layouts.admin')
@section('title','Seller Compliance')
@section('subtitle','Real seller account states and flagged product records.')
@section('active','compliance')
@section('content')
<div class="ad-live-stack" style="display:grid;gap:16px">
<div class="ad-page-head"><div><span class="ad-overline">Compliance</span><h2>Seller compliance</h2><p>Uses seller accounts and product moderation state from MySQL.</p></div></div>
<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px">@foreach(['active'=>'Active sellers','pending'=>'Pending sellers','flagged'=>'Flagged products','suspended'=>'Suspended sellers'] as $k=>$l)<div class="ad-card ad-card-body"><small>{{ $l }}</small><h2>{{ number_format($complianceStats[$k] ?? 0) }}</h2></div>@endforeach</div>
<div class="ad-card"><div class="ad-card-head"><div><h2>Flagged products</h2><p>Products requiring administrator review</p></div></div><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Product</th><th>Seller</th><th>Category</th><th>Admin status</th><th>Actions</th></tr></thead><tbody>@forelse($flaggedProducts as $product)<tr><td><strong>{{ $product->name }}</strong><small>{{ $product->sku }}</small></td><td>{{ $product->seller?->name }}</td><td>{{ $product->category?->name ?? 'Uncategorized' }}</td><td>{{ str($product->admin_status)->headline() }}</td><td><div class="ad-inline-actions"><form method="POST" action="{{ route('admin.products.moderate',$product) }}">@csrf<input type="hidden" name="action" value="approve"><button class="ad-btn ad-btn-primary ad-btn-sm">Approve</button></form><form method="POST" action="{{ route('admin.products.moderate',$product) }}">@csrf<input type="hidden" name="action" value="archive"><button class="ad-btn ad-btn-danger-soft ad-btn-sm">Archive</button></form></div></td></tr>@empty<tr><td colspan="5">No flagged products.</td></tr>@endforelse</tbody></table></div></div>
<div class="ad-card"><div class="ad-card-head"><div><h2>Sellers</h2><p>{{ number_format($sellerRecords->total()) }} seller accounts</p></div></div><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Seller</th><th>Email</th><th>Status</th><th>Products</th><th>Account</th></tr></thead><tbody>@forelse($sellerRecords as $seller)<tr><td><strong>{{ $seller->name }}</strong><small>{{ $seller->business_name ?: $seller->store_name }}</small></td><td>{{ $seller->email }}</td><td>{{ str($seller->status)->headline() }}</td><td>{{ number_format($sellerProductCounts[$seller->id] ?? 0) }}</td><td><a class="ad-btn ad-btn-secondary ad-btn-sm" href="{{ route('admin.users.show',$seller) }}">View account</a></td></tr>@empty<tr><td colspan="5">No seller accounts.</td></tr>@endforelse</tbody></table></div><div class="ad-card-body">{{ $sellerRecords->links() }}</div></div>
</div>
@endsection
