@extends('layouts.admin')
@section('title','Finance')
@section('subtitle','Transaction-backed marketplace totals and commission calculations.')
@section('active','finance')
@section('content')
<div style="display:grid;gap:16px">
<div class="ad-page-head"><div><span class="ad-overline">Finance</span><h2>Marketplace finance</h2><p>Commission uses the same persisted platform rate used by Seller finance.</p></div><a class="ad-btn ad-btn-secondary" href="{{ route('admin.finance.export') }}">Export CSV</a></div>
<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px"><div class="ad-card ad-card-body"><small>Eligible gross</small><h2>₱{{ number_format($gross,2) }}</h2></div><div class="ad-card ad-card-body"><small>Commission ({{ number_format($rate*100,2) }}%)</small><h2>₱{{ number_format($commission,2) }}</h2></div><div class="ad-card ad-card-body"><small>Seller net</small><h2>₱{{ number_format($net,2) }}</h2></div><div class="ad-card ad-card-body"><small>Pending settlement</small><h2>₱{{ number_format($pendingSettlement,2) }}</h2><small>{{ number_format($pendingCount) }} transactions</small></div></div>
<form class="ad-card ad-card-body ad-filter-bar" method="GET"><div class="ad-inline-actions"><input name="q" value="{{ request('q') }}" placeholder="Transaction or order"><select name="status"><option value="">All statuses</option>@foreach(['pending','processing','paid','completed','failed','refunded'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ str($s)->headline() }}</option>@endforeach</select><button class="ad-btn ad-btn-primary">Filter</button><a class="ad-btn ad-btn-secondary" href="{{ route('admin.finance') }}">Reset</a></div></form>
<div class="ad-card"><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Transaction</th><th>Order</th><th>Buyer</th><th>Seller</th><th>Gross</th><th>Commission</th><th>Net</th><th>Method</th><th>Status</th></tr></thead><tbody>@forelse($transactionRecords as $transaction)@php($fee=round((float)$transaction->amount*$rate,2))<tr><td><strong>{{ $transaction->transaction_number }}</strong></td><td>{{ $transaction->order?->order_number }}</td><td>{{ $transaction->buyer?->name }}</td><td>{{ $transaction->order?->seller?->name }}</td><td>₱{{ number_format((float)$transaction->amount,2) }}</td><td>₱{{ number_format($fee,2) }}</td><td>₱{{ number_format((float)$transaction->amount-$fee,2) }}</td><td>{{ strtoupper($transaction->method) }}</td><td>{{ str($transaction->status)->headline() }}</td></tr>@empty<tr><td colspan="9">No transactions found.</td></tr>@endforelse</tbody></table></div><div class="ad-card-body">{{ $transactionRecords->links() }}</div></div>
</div>
@endsection
