@extends('layouts.admin')

@section('title', 'Communication')
@section('subtitle', 'Manage support conversations and publish targeted platform announcements.')
@section('active', 'messages')

@section('content')
@php $tab = request('tab', 'messages'); @endphp
<div class="ad-page">
    <div class="ad-page-head"><div><span class="ad-overline">Platform communication</span><h2>{{ $tab === 'announcements' ? 'Announcements' : 'Support messages' }}</h2><p>Keep conversations clear, role-aware, and connected to marketplace records.</p></div>@if($tab === 'announcements')<button class="ad-btn ad-btn-primary" type="button" data-demo-action="Announcement composer ready">New announcement</button>@endif</div>
    <div class="ad-tabs"><a class="ad-tab {{ $tab === 'messages' ? 'is-active' : '' }}" href="{{ route('admin.messages', ['tab' => 'messages']) }}">Messages <b>4</b></a><a class="ad-tab {{ $tab === 'announcements' ? 'is-active' : '' }}" href="{{ route('admin.messages', ['tab' => 'announcements']) }}">Announcements</a></div>

    @if($tab === 'announcements')
        <section class="ad-dashboard-split">
            <article class="ad-card"><header class="ad-card-head"><div><span class="ad-overline">Compose</span><h2>Create announcement</h2><p>Send only to the roles that need the update.</p></div></header><form class="ad-settings-section" data-demo-form data-success-message="Announcement scheduled for publishing"><div class="ad-form-grid"><label class="ad-field"><span>Audience</span><select><option>All platform users</option><option>Buyers only</option><option>Sellers only</option><option>Logistics centers only</option><option>Riders / couriers only</option></select></label><label class="ad-field"><span>Priority</span><select><option>Standard</option><option>Important</option><option>Urgent</option></select></label><label class="ad-field is-full"><span>Announcement title</span><input placeholder="Short, specific title"></label><label class="ad-field is-full"><span>Message</span><textarea rows="7" placeholder="Write the announcement details..."></textarea></label><label class="ad-field"><span>Publish date</span><input type="datetime-local"></label><label class="ad-field"><span>Delivery channels</span><select><option>In-app notification</option><option>In-app + email</option></select></label></div><div class="ad-inline-actions"><button class="ad-btn ad-btn-primary" type="submit">Publish announcement</button><button class="ad-btn ad-btn-secondary" type="button" data-demo-action="Announcement draft saved">Save draft</button></div></form></article>
            <aside class="ad-card"><header class="ad-card-head"><div><span class="ad-overline">Published</span><h3>Recent announcements</h3><p>Latest messages sent by Admin.</p></div></header><div class="ad-queue"><div class="ad-queue-item"><span class="ad-queue-icon">A</span><span class="ad-queue-copy"><strong>Scheduled maintenance</strong><span>All users · Sep 3 · 12,204 delivered</span></span><span class="ad-status is-completed">Sent</span></div><div class="ad-queue-item"><span class="ad-queue-icon">S</span><span class="ad-queue-copy"><strong>Updated product policy</strong><span>Sellers · Sep 1 · 1,902 delivered</span></span><span class="ad-status is-completed">Sent</span></div><div class="ad-queue-item is-warning"><span class="ad-queue-icon">L</span><span class="ad-queue-copy"><strong>Holiday pickup schedule</strong><span>Logistics · Scheduled Sep 6</span></span><span class="ad-status is-pending">Scheduled</span></div></div></aside>
        </section>
    @else
        <section class="ad-messages">
            <aside class="ad-conversations"><div class="ad-conversation-head"><h2>Conversations</h2><span class="ad-status is-open">4 open</span></div><div class="ad-conversation-list">
                <button type="button" class="ad-conversation is-active" data-conversation data-name="Angela Cruz" data-subject="Buyer · Order #LK-10482"><span class="ad-avatar is-soft">AC</span><span><strong>Angela Cruz</strong><p>My order status has not updated...</p></span><time>10:42</time></button>
                <button type="button" class="ad-conversation" data-conversation data-name="LIKHA Studio" data-subject="Seller · Compliance question"><span class="ad-avatar is-soft">LS</span><span><strong>LIKHA Studio</strong><p>We submitted the renewed permit...</p></span><time>09:18</time></button>
                <button type="button" class="ad-conversation" data-conversation data-name="NorthLink Hub" data-subject="Logistics · Delivery exception"><span class="ad-avatar is-soft">NH</span><span><strong>NorthLink Hub</strong><p>Requesting help with a duplicate...</p></span><time>Yesterday</time></button>
                <button type="button" class="ad-conversation" data-conversation data-name="Juan Dela Cruz" data-subject="Rider · Account access"><span class="ad-avatar is-soft">JD</span><span><strong>Juan Dela Cruz</strong><p>My account is showing under review...</p></span><time>Yesterday</time></button>
            </div></aside>
            <main class="ad-chat"><header class="ad-chat-head"><div><h2 data-chat-name>Angela Cruz</h2><p data-chat-subject>Buyer · Order #LK-10482</p></div><div class="ad-inline-actions"><button class="ad-btn ad-btn-secondary ad-btn-sm" data-demo-action="Opening linked order">View order</button><button class="ad-btn ad-btn-secondary ad-btn-sm" data-demo-action="Conversation assigned to you">Assign</button></div></header><div class="ad-chat-body" data-chat-body><div class="ad-bubble">Hello, my order status has not updated since this morning. Can you check it?<time>10:36 AM</time></div><div class="ad-bubble is-admin">Hi Angela. I can see that the seller prepared the parcel and J&T has a pickup scheduled today. I’ll monitor the first courier scan for you.<time>10:39 AM</time></div><div class="ad-bubble">Thank you. Will I receive a notification when it is picked up?<time>10:42 AM</time></div></div><form class="ad-chat-compose" data-chat-form><input type="text" placeholder="Write a clear response..." aria-label="Message"><button type="submit" class="ad-btn ad-btn-primary">Send</button></form></main>
        </section>
    @endif
</div>
@endsection
