@extends('layouts.admin')
@section('title','Messages & Announcements')
@section('subtitle','Real administrator conversations and persisted announcements.')
@section('active','messages')
@php($tab=request('tab','messages'))
@section('content')
<div style="display:grid;gap:16px">
@if(session('success'))<div class="ad-card ad-card-body">{{ session('success') }}</div>@endif
<div class="ad-page-head"><div><span class="ad-overline">Communication</span><h2>{{ $tab==='announcements' ? 'Announcements' : 'Messages' }}</h2><p>No frontend-only conversation or announcement data is used.</p></div><div class="ad-inline-actions"><a class="ad-btn {{ $tab==='messages'?'ad-btn-primary':'ad-btn-secondary' }}" href="{{ route('admin.messages',['tab'=>'messages']) }}">Messages</a><a class="ad-btn {{ $tab==='announcements'?'ad-btn-primary':'ad-btn-secondary' }}" href="{{ route('admin.messages',['tab'=>'announcements']) }}">Announcements</a></div></div>
@if($tab==='announcements')
<div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px"><div class="ad-card"><div class="ad-card-head"><div><h2>Create announcement</h2><p>Publish now, schedule, or save as draft.</p></div></div><div class="ad-card-body"><form style="display:grid;gap:12px" method="POST" action="{{ route('admin.announcements.store') }}">@csrf<label class="ad-field"><span>Audience</span><select name="audience">@foreach(['all'=>'All platform users','buyers'=>'Buyers','sellers'=>'Sellers','logistics'=>'Logistics','riders'=>'Riders'] as $v=>$l)<option value="{{ $v }}">{{ $l }}</option>@endforeach</select></label><label class="ad-field"><span>Priority</span><select name="priority">@foreach(['standard','important','urgent'] as $v)<option value="{{ $v }}">{{ str($v)->headline() }}</option>@endforeach</select></label><label class="ad-field"><span>Title</span><input name="title" required maxlength="180"></label><label class="ad-field"><span>Message</span><textarea name="body" rows="7" required></textarea></label><label class="ad-field"><span>Publish date/time (optional)</span><input type="datetime-local" name="publish_at"></label><div class="ad-inline-actions"><button class="ad-btn ad-btn-primary" name="intent" value="publish">Publish / schedule</button><button class="ad-btn ad-btn-secondary" name="intent" value="draft">Save draft</button></div></form></div></div>
<div class="ad-card"><div class="ad-card-head"><div><h2>Announcement history</h2><p>Stored in admin_announcements.</p></div></div><div class="ad-card-body" style="display:grid;gap:10px">@forelse($announcementRecords as $a)<div style="padding:12px;border:1px solid var(--ad-border);border-radius:12px"><strong>{{ $a->title }}</strong><p>{{ $a->body }}</p><small>{{ str($a->audience)->headline() }} · {{ str($a->priority)->headline() }} · {{ str($a->status)->headline() }} @if($a->publish_at)· {{ $a->publish_at->format('M d, Y H:i') }}@endif</small></div>@empty<p>No announcements yet.</p>@endforelse</div><div class="ad-card-body">{{ $announcementRecords->links() }}</div></div></div>
@else
<div style="display:grid;grid-template-columns:320px minmax(0,1fr);gap:16px"><aside class="ad-card"><div class="ad-card-head"><div><h2>Conversations</h2></div></div><div class="ad-card-body" style="display:grid;gap:12px"><form method="GET" action="{{ route('admin.messages') }}" style="display:grid;gap:8px"><input type="hidden" name="tab" value="messages"><label class="ad-field"><span>Start conversation</span><select name="partner" required><option value="">Select an active user</option>@foreach($messageRecipients as $recipient)<option value="{{ $recipient->id }}" @selected($selectedPartner?->id === $recipient->id)>{{ $recipient->name }} · {{ str($recipient->primary_role)->headline() }} · {{ $recipient->email }}</option>@endforeach</select></label><button class="ad-btn ad-btn-primary" type="submit">Open conversation</button></form>@forelse($conversations as $conversation)<a class="ad-btn ad-btn-secondary" style="justify-content:space-between" href="{{ route('admin.messages',['partner'=>$conversation['user']->id]) }}"><span>{{ $conversation['user']->name }}<small style="display:block">{{ str($conversation['user']->primary_role)->headline() }}</small></span>@if($conversation['unread'])<b>{{ $conversation['unread'] }}</b>@endif</a>@empty<p>No administrator conversations yet.</p>@endforelse</div></aside><main class="ad-card"><div class="ad-card-head"><div><h2>{{ $selectedPartner?->name ?? 'Select a conversation' }}</h2><p>{{ $selectedPartner ? str($selectedPartner->primary_role)->headline().' · '.$selectedPartner->email : 'Choose a user from the left.' }}</p></div></div><div class="ad-card-body" style="display:grid;gap:10px;max-height:520px;overflow:auto">@forelse($thread as $message)<div style="padding:12px;border:1px solid var(--ad-border);border-radius:12px;{{ $message->sender_id===auth()->id() ? 'background:var(--ad-blue-soft)' : '' }}"><strong>{{ $message->sender?->name }}</strong><p style="white-space:pre-wrap">{{ $message->body }}</p><small>{{ $message->created_at?->format('M d, Y H:i') }} @if($message->order)· Order {{ $message->order->order_number }}@endif</small></div>@empty<p>No messages in this conversation.</p>@endforelse</div>@if($selectedPartner)<div class="ad-card-body"><form class="ad-inline-actions" method="POST" action="{{ route('admin.messages.send') }}">@csrf<input type="hidden" name="recipient_id" value="{{ $selectedPartner->id }}"><input name="body" required maxlength="5000" style="flex:1;padding:10px 12px;border:1px solid var(--ad-border);border-radius:10px" placeholder="Write a response"><button class="ad-btn ad-btn-primary">Send</button></form></div>@endif</main></div>
@endif
</div>
@endsection
