@extends('layouts.admin')
@section('title','Product Management')
@section('subtitle','Database-backed catalog moderation, categories, search, and export.')
@section('active','products')
@section('content')
<style>
.ad-live-grid{display:grid;gap:16px}.ad-live-grid.cols-4{grid-template-columns:repeat(4,minmax(0,1fr))}.ad-live-grid.cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}.ad-live-stat{padding:16px}.ad-live-stat span{display:block;color:var(--ad-muted);font-size:9px}.ad-live-stat strong{display:block;margin-top:5px;font-size:20px}.ad-live-form{display:grid;gap:12px}.ad-live-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ad-live-form .ad-field input,.ad-live-form .ad-field select,.ad-live-form .ad-field textarea,.ad-filter-bar input,.ad-filter-bar select{width:100%;padding:10px 12px;border:1px solid var(--ad-border);border-radius:10px;background:var(--ad-card);color:var(--ad-text)}.ad-live-stack{display:grid;gap:16px}.ad-live-actions{display:flex;gap:7px;flex-wrap:wrap}.ad-live-success{padding:12px 14px;border:1px solid #b7dfc9;border-radius:12px;background:#eaf7ef;color:#256f4a}@media(max-width:900px){.ad-live-grid.cols-4,.ad-live-grid.cols-2,.ad-live-form-grid{grid-template-columns:1fr}}
</style>
<div class="ad-live-stack">
@if(session('success'))<div class="ad-live-success">{{ session('success') }}</div>@endif
<div class="ad-page-head"><div><span class="ad-overline">Catalog</span><h2>Product management</h2><p>Every count and row below comes from the products/categories tables.</p></div><a class="ad-btn ad-btn-secondary" href="{{ route('admin.products.export') }}">Export CSV</a></div>
<div class="ad-live-grid cols-4">
@foreach(['total'=>'Total products','active'=>'Active listings','flagged'=>'Flagged','archived'=>'Archived'] as $key=>$label)<div class="ad-card ad-live-stat"><span>{{ $label }}</span><strong>{{ number_format($stats[$key] ?? 0) }}</strong></div>@endforeach
</div>
<form class="ad-card ad-card-body ad-filter-bar" method="GET" action="{{ route('admin.products') }}">
<div class="ad-live-form-grid"><label class="ad-field"><span>Search</span><input name="q" value="{{ request('q') }}" placeholder="Product, SKU, or seller"></label><label class="ad-field"><span>Visibility</span><select name="visibility"><option value="">All</option><option value="active" @selected(request('visibility')==='active')>Active</option><option value="inactive" @selected(request('visibility')==='inactive')>Inactive</option></select></label><div class="ad-live-actions" style="align-items:end"><button class="ad-btn ad-btn-primary">Apply filters</button><a class="ad-btn ad-btn-secondary" href="{{ route('admin.products') }}">Reset</a></div></div>
</form>
<div class="ad-card"><div class="ad-card-head"><div><h2>Products</h2><p>{{ number_format($productRecords->total()) }} matching records</p></div></div><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Product</th><th>Seller</th><th>Category</th><th>Price</th><th>Stock</th><th>Listing</th><th>Admin</th><th>Actions</th></tr></thead><tbody>
@forelse($productRecords as $product)<tr><td><strong>{{ $product->name }}</strong><small>{{ $product->variants->pluck('sku')->filter()->join(', ') ?: 'No SKU' }}</small></td><td>{{ $product->seller?->name ?? 'Deleted seller' }}</td><td>{{ $product->category?->name ?? 'Uncategorized' }}</td><td>₱{{ number_format($product->min_price_minor / 100, 2) }}</td><td>{{ number_format($product->variants->sum('stock')) }}</td><td>{{ $product->is_active ? 'Active' : 'Inactive' }}</td><td>Canonical</td><td><div class="ad-live-actions">@foreach(['archive'=>'Archive','restore'=>'Restore'] as $action=>$label)<form method="POST" action="{{ route('admin.products.moderate',$product) }}">@csrf<input type="hidden" name="action" value="{{ $action }}"><button class="ad-btn ad-btn-secondary ad-btn-sm">{{ $label }}</button></form>@endforeach</div></td></tr>@empty<tr><td colspan="8">No products found.</td></tr>@endforelse
</tbody></table></div><div class="ad-card-body">{{ $productRecords->links() }}</div></div>
<div class="ad-live-grid cols-2"><div class="ad-card"><div class="ad-card-head"><div><h2>Categories</h2><p>Root marketplace categories</p></div></div><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Name</th><th>Products</th><th>Active</th><th>Status</th><th>Update</th></tr></thead><tbody>@forelse($categoryRecords as $category)<tr><td><strong>{{ $category->name }}</strong></td><td>{{ $category->products_count }}</td><td>{{ $category->active_products_count }}</td><td>{{ str($category->status)->headline() }}</td><td><form class="ad-live-actions" method="POST" action="{{ route('admin.categories.update',$category) }}">@csrf @method('PATCH')<input name="name" value="{{ $category->name }}" required style="max-width:150px"><input type="hidden" name="description" value="{{ $category->description }}"><select name="status"><option value="active" @selected($category->status==='active')>Active</option><option value="inactive" @selected($category->status==='inactive')>Inactive</option></select><button class="ad-btn ad-btn-secondary ad-btn-sm">Save</button></form></td></tr>@empty<tr><td colspan="5">No categories yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="ad-card"><div class="ad-card-head"><div><h2>Add category</h2><p>Creates a real category record.</p></div></div><div class="ad-card-body"><form class="ad-live-form" method="POST" action="{{ route('admin.categories.store') }}">@csrf<label class="ad-field"><span>Name</span><input name="name" value="{{ old('name') }}" required></label><label class="ad-field"><span>Description</span><textarea name="description" rows="4">{{ old('description') }}</textarea></label><label class="ad-field"><span>Status</span><select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button class="ad-btn ad-btn-primary">Create category</button></form></div></div></div>
</div>
@endsection
