@extends('layouts.admin')
@section('title','Reports')
@section('subtitle','Sales and 10% platform commission reporting from canonical seller orders.')
@section('active','reports')
@section('content')
<div style="display:grid;gap:16px"><div class="ad-page-head"><div><span class="ad-overline">Reports</span><h2>Sales and commission report</h2><p>Filter real seller orders by status and date.</p></div><a class="ad-btn ad-btn-secondary" href="{{ route('admin.reports.export',request()->query()) }}">Download Commission CSV</a></div>
<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px"><div class="ad-card ad-card-body"><small>Gross order value</small><h2>PHP {{ number_format($gross,2) }}</h2></div><div class="ad-card ad-card-body"><small>Platform commission</small><h2>PHP {{ number_format($commission,2) }}</h2></div><div class="ad-card ad-card-body"><small>Completed</small><h2>{{ $completed }}</h2></div><div class="ad-card ad-card-body"><small>Cancelled</small><h2>{{ $cancelled }}</h2></div></div>
<form class="ad-card ad-card-body ad-filter-bar" method="GET"><div class="ad-inline-actions"><select name="status"><option value="">All statuses</option>@foreach(['PLACED','CONFIRMED','PREPARING','READY_FOR_PICKUP','PICKED_UP','COMPLETED','CANCELLED'] as $value)<option value="{{ $value }}" @selected(request('status')===$value)>{{ str($value)->headline() }}</option>@endforeach</select><input type="date" name="date_from" value="{{ request('date_from') }}"><input type="date" name="date_to" value="{{ request('date_to') }}"><button class="ad-btn ad-btn-primary">Apply</button></div></form>
<div class="ad-card"><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Order</th><th>Buyer</th><th>Seller</th><th>Total</th><th>Payment</th><th>Status</th><th>Created</th></tr></thead><tbody>@forelse($orderRecords as $order)<tr><td><strong>{{ $order->seller_order_number }}</strong></td><td>{{ $order->order?->buyer?->name }}</td><td>{{ $order->sellerProfile?->business_name }}</td><td>PHP {{ number_format((float)$order->grand_total,2) }}</td><td>{{ str($order->order?->payments?->sortByDesc('id')->first()?->status ?? 'PENDING')->headline() }}</td><td>{{ str($order->status)->headline() }}</td><td>{{ $order->created_at?->format('M d, Y H:i') }}</td></tr>@empty<tr><td colspan="7">No orders match this report.</td></tr>@endforelse</tbody></table></div><div class="ad-card-body">{{ $orderRecords->links() }}</div></div></div>
@endsection
