@extends('layouts.admin')
@section('title','Reports')
@section('subtitle','Live order reporting with date/status filters and CSV export.')
@section('active','reports')
@section('content')
<div style="display:grid;gap:16px">
<div class="ad-page-head"><div><span class="ad-overline">Reports</span><h2>Order report</h2><p>All figures are calculated from the filtered orders query.</p></div><a class="ad-btn ad-btn-secondary" href="{{ route('admin.reports.export',request()->query()) }}">Download CSV</a></div>
<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px"><div class="ad-card ad-card-body"><small>Gross order value</small><h2>₱{{ number_format($gross,2) }}</h2></div><div class="ad-card ad-card-body"><small>Platform commission</small><h2>₱{{ number_format($commission,2) }}</h2></div><div class="ad-card ad-card-body"><small>Completed</small><h2>{{ number_format($completed) }}</h2></div><div class="ad-card ad-card-body"><small>Cancelled</small><h2>{{ number_format($cancelled) }}</h2></div></div>
<form class="ad-card ad-card-body ad-filter-bar" method="GET"><div class="ad-inline-actions"><select name="status"><option value="">All statuses</option>@foreach(['pending','confirmed','processing','preparing','ready_for_pickup','picked_up','sorting','assigned','out_for_delivery','delivered','completed','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ str($s)->headline() }}</option>@endforeach</select><input type="date" name="date_from" value="{{ request('date_from') }}"><input type="date" name="date_to" value="{{ request('date_to') }}"><button class="ad-btn ad-btn-primary">Apply</button><a class="ad-btn ad-btn-secondary" href="{{ route('admin.reports') }}">Reset</a></div></form>
<div class="ad-card"><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Order</th><th>Buyer</th><th>Seller</th><th>Total</th><th>Payment</th><th>Status</th><th>Created</th></tr></thead><tbody>@forelse($orderRecords as $order)<tr><td><strong>{{ $order->order_number }}</strong></td><td>{{ $order->buyer?->name }}</td><td>{{ $order->seller?->name }}</td><td>₱{{ number_format((float)$order->total_amount,2) }}</td><td>{{ str($order->payment_status)->headline() }}</td><td>{{ str($order->status)->headline() }}</td><td>{{ $order->created_at?->format('M d, Y H:i') }}</td></tr>@empty<tr><td colspan="7">No orders match this report.</td></tr>@endforelse</tbody></table></div><div class="ad-card-body">{{ $orderRecords->links() }}</div></div>
</div>
@endsection
