@extends('layouts.admin')
@section('title','System Management')
@section('subtitle','Persisted platform settings, policies, and audit history.')
@section('active','settings')
@php($tab=request('tab','platform'))
@section('content')
<div style="display:grid;gap:16px">@if(session('success'))<div class="ad-card ad-card-body">{{ session('success') }}</div>@endif
<div class="ad-page-head"><div><span class="ad-overline">System</span><h2>System management</h2><p>Changes on this page persist to MySQL.</p></div><div class="ad-inline-actions">@foreach(['platform'=>'Platform','policies'=>'Policies','audit'=>'Audit logs'] as $k=>$l)<a class="ad-btn {{ $tab===$k?'ad-btn-primary':'ad-btn-secondary' }}" href="{{ route('admin.settings',['tab'=>$k]) }}">{{ $l }}</a>@endforeach</div></div>
@if($tab==='platform')<div class="ad-card"><div class="ad-card-head"><div><h2>Marketplace configuration</h2></div></div><div class="ad-card-body"><form style="display:grid;gap:12px" method="POST" action="{{ route('admin.settings.update') }}">@csrf @method('PATCH')<label class="ad-field"><span>Marketplace name</span><input name="marketplace_name" value="{{ old('marketplace_name',$settings['marketplace_name']) }}" required></label><label class="ad-field"><span>Support email</span><input type="email" name="support_email" value="{{ old('support_email',$settings['support_email']) }}"></label><label class="ad-field"><span>Seller commission (%)</span><input type="number" step="0.01" min="0" max="100" name="seller_commission_rate" value="{{ old('seller_commission_rate',$settings['seller_commission_rate']*100) }}" required></label><label><input type="hidden" name="registration_enabled" value="0"><input type="checkbox" name="registration_enabled" value="1" @checked(old('registration_enabled',$settings['registration_enabled']))> Allow new registrations</label><label><input type="hidden" name="automated_product_risk_signals" value="0"><input type="checkbox" name="automated_product_risk_signals" value="1" @checked(old('automated_product_risk_signals',$settings['automated_product_risk_signals']))> Automated product risk signals</label><button class="ad-btn ad-btn-primary">Save settings</button></form></div></div>
@elseif($tab==='policies')<div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px"><div class="ad-card"><div class="ad-card-head"><div><h2>Create policy</h2></div></div><div class="ad-card-body"><form style="display:grid;gap:12px" method="POST" action="{{ route('admin.policies.store') }}">@csrf<label class="ad-field"><span>Title</span><input name="title" required></label><label class="ad-field"><span>Revision</span><input name="revision"></label><label class="ad-field"><span>Body</span><textarea name="body" rows="8" required></textarea></label><label class="ad-field"><span>Status</span><select name="status"><option value="draft">Draft</option><option value="published">Published</option></select></label><button class="ad-btn ad-btn-primary">Save policy</button></form></div></div><div class="ad-card"><div class="ad-card-head"><div><h2>Policies</h2></div></div><div class="ad-card-body" style="display:grid;gap:12px">@forelse($policies as $policy)<form style="display:grid;gap:8px;padding:12px;border:1px solid var(--ad-border);border-radius:12px" method="POST" action="{{ route('admin.policies.update',$policy) }}">@csrf @method('PATCH')<input name="title" value="{{ $policy->title }}" required><input name="revision" value="{{ $policy->revision }}"><textarea name="body" rows="5" required>{{ $policy->body }}</textarea><select name="status"><option value="draft" @selected($policy->status==='draft')>Draft</option><option value="published" @selected($policy->status==='published')>Published</option></select><button class="ad-btn ad-btn-secondary ad-btn-sm">Update</button></form>@empty<p>No policies yet.</p>@endforelse</div><div class="ad-card-body">{{ $policies->links() }}</div></div></div>
@else<div class="ad-card"><div class="ad-card-head"><div><h2>Audit log</h2><p>Administrator actions recorded by the working Admin flows.</p></div><a class="ad-btn ad-btn-secondary" href="{{ route('admin.audit.export') }}">Export CSV</a></div><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Target</th><th>Description</th><th>IP</th></tr></thead><tbody>@forelse($auditLogs as $log)<tr><td>{{ $log->created_at?->format('M d, Y H:i:s') }}</td><td>{{ $log->actor?->email ?? 'System' }}</td><td>{{ $log->action }}</td><td>{{ $log->target_type }} {{ $log->target_id }}</td><td style="white-space:normal">{{ $log->description }}</td><td>{{ $log->ip_address }}</td></tr>@empty<tr><td colspan="6">No audit entries yet.</td></tr>@endforelse</tbody></table></div><div class="ad-card-body">{{ $auditLogs->links() }}</div></div>@endif
</div>
@endsection
