@extends('layouts.admin')

@section('title', 'System Management')
@section('subtitle', 'Maintain platform policies, operational settings, and traceable audit records.')
@section('active', 'settings')

@section('content')
@php
    $tab = request('tab', 'policies');
    $tabs = ['policies' => 'Platform Policies', 'platform' => 'Platform Settings', 'audit' => 'Audit Logs'];
@endphp
<div class="ad-page">
    <div class="ad-page-head"><div><span class="ad-overline">System governance</span><h2>{{ $tabs[$tab] ?? 'Platform Policies' }}</h2><p>High-impact settings should be deliberate, permission-controlled, and auditable.</p></div>@if($tab !== 'audit')<button class="ad-btn ad-btn-primary" type="button" data-demo-action="Changes saved for this frontend preview">Save changes</button>@else<button class="ad-btn ad-btn-secondary" type="button" data-demo-action="Audit logs exported">Export logs</button>@endif</div>
    <section class="ad-settings-layout">
        <nav class="ad-card ad-settings-nav">@foreach($tabs as $key => $label)<a class="{{ $tab === $key ? 'is-active' : '' }}" href="{{ route('admin.settings', ['tab' => $key]) }}">{{ $label }}</a>@endforeach</nav>
        <div class="ad-card">
            @if($tab === 'platform')
                <form class="ad-settings-section" data-demo-form data-success-message="Platform settings saved"><h2>Marketplace configuration</h2><p>General platform behavior and operational controls.</p><div class="ad-form-grid"><label class="ad-field"><span>Marketplace name</span><input value="LIKHAE Marketplace"></label><label class="ad-field"><span>Support email</span><input type="email" value="support@likhae.ph"></label><label class="ad-field"><span>Default currency</span><select><option>PHP — Philippine Peso</option></select></label><label class="ad-field"><span>Platform commission</span><input value="10%" readonly></label></div><div><div class="ad-setting-row"><div><strong>New registrations</strong><p>Allow new buyer, seller, and logistics applications.</p></div><label class="ad-switch"><input type="checkbox" checked><span></span></label></div><div class="ad-setting-row"><div><strong>Automated product risk signals</strong><p>Flag listings for human review; never remove automatically.</p></div><label class="ad-switch"><input type="checkbox" checked><span></span></label></div><div class="ad-setting-row"><div><strong>Maintenance notice</strong><p>Display a platform-wide maintenance banner.</p></div><label class="ad-switch"><input type="checkbox"><span></span></label></div></div><button class="ad-btn ad-btn-primary" type="submit">Save platform settings</button></form>
            @elseif($tab === 'audit')
                <div id="audit-table"><div class="ad-filter-bar"><label class="ad-filter-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input type="search" data-filter-input="#audit-table" placeholder="Search actor, action, or record ID"></label><select class="ad-select"><option>All action types</option><option>Account enforcement</option><option>Product moderation</option><option>Policy change</option></select></div><div class="ad-table-wrap"><table class="ad-table"><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Target</th><th>Reason / change</th><th>IP address</th><th>Result</th></tr></thead><tbody><tr data-filter-item><td>Sep 4, 10:51 AM</td><td><strong>Admin User</strong></td><td>Listing removed</td><td>PRD-8448</td><td>Prohibited weapon evidence confirmed</td><td>192.168.1.24</td><td><span class="ad-status is-completed">Success</span></td></tr><tr data-filter-item><td>Sep 4, 10:12 AM</td><td><strong>Admin User</strong></td><td>Violation notice</td><td>USR-10078</td><td>Misleading listing information</td><td>192.168.1.24</td><td><span class="ad-status is-completed">Success</span></td></tr><tr data-filter-item><td>Sep 4, 9:32 AM</td><td><strong>Finance Admin</strong></td><td>Settlement retried</td><td>TXN-980138</td><td>Payment provider timeout</td><td>192.168.1.19</td><td><span class="ad-status is-pending">Pending</span></td></tr><tr data-filter-item><td>Sep 3, 5:15 PM</td><td><strong>Super Admin</strong></td><td>Policy published</td><td>POL-012</td><td>Restricted products revision 3.2</td><td>192.168.1.10</td><td><span class="ad-status is-completed">Success</span></td></tr></tbody></table></div></div>
            @else
                <div class="ad-settings-section"><h2>Platform policies</h2><p>Published rules used for registration, marketplace moderation, and disputes.</p><div class="ad-card-list"><div class="ad-setting-row"><div><strong>Restricted and prohibited products</strong><p>Revision 3.2 · Published Sep 3, 2026 · Applies to all sellers</p></div><div class="ad-inline-actions"><span class="ad-status is-active">Published</span><button class="ad-btn ad-btn-secondary ad-btn-sm" data-demo-action="Opening prohibited-products policy">Edit</button></div></div><div class="ad-setting-row"><div><strong>Seller compliance standard</strong><p>Revision 2.8 · Published Aug 20, 2026</p></div><div class="ad-inline-actions"><span class="ad-status is-active">Published</span><button class="ad-btn ad-btn-secondary ad-btn-sm" data-demo-action="Opening seller policy">Edit</button></div></div><div class="ad-setting-row"><div><strong>Returns and refund policy</strong><p>Revision 4.1 · Published Aug 5, 2026</p></div><div class="ad-inline-actions"><span class="ad-status is-active">Published</span><button class="ad-btn ad-btn-secondary ad-btn-sm" data-demo-action="Opening returns policy">Edit</button></div></div><div class="ad-setting-row"><div><strong>Privacy and account deletion</strong><p>Revision 1.9 · Draft updated Sep 2, 2026</p></div><div class="ad-inline-actions"><span class="ad-status is-pending">Draft</span><button class="ad-btn ad-btn-secondary ad-btn-sm" data-demo-action="Opening privacy policy draft">Review</button></div></div></div><button class="ad-btn ad-btn-primary" type="button" data-demo-action="New policy editor opened">Create policy</button></div>
            @endif
        </div>
    </section>
</div>
@endsection
