@extends('Logistics.app')
@section('title','Parcels - LIKHAE Logistics')
@section('content')
<div class="space-y-6">
    <header class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-xs font-bold uppercase text-primary">Parcel Management</p><h1 class="mt-2 text-2xl font-bold text-ink">All Parcels</h1><p class="mt-2 text-sm text-muted">Connected shipment records for this sorting center.</p></div><div class="flex gap-2"><a href="{{ route('logistics.parcels.receive') }}" class="bg-primary px-4 py-2 font-semibold text-white">Receive Parcel</a><a href="{{ route('logistics.parcels.tracking') }}" class="border border-line px-4 py-2 font-semibold">Track Parcel</a></div></header>
    <nav class="flex flex-wrap gap-2">@foreach([''=>'All','PICKED_UP'=>'Incoming','AT_SORTING_CENTER'=>'For Sorting','SORTED'=>'Sorted','ASSIGNED_TO_RIDER'=>'Assigned','OUT_FOR_DELIVERY'=>'Out for Delivery','DELIVERED'=>'Delivered'] as $key=>$label)<a href="{{ route('logistics.parcels',['status'=>$key]) }}" class="border border-line px-3 py-2 text-sm {{ $status===$key?'bg-primary text-white':'' }}">{{ $label }}</a>@endforeach</nav>
    <div class="overflow-x-auto border border-line bg-surface"><table class="min-w-full text-left text-sm"><thead class="bg-page-secondary text-xs uppercase text-muted"><tr><th class="p-4">Tracking</th><th class="p-4">Order</th><th class="p-4">Seller</th><th class="p-4">Destination</th><th class="p-4">Area</th><th class="p-4">Status</th><th></th></tr></thead><tbody class="divide-y divide-line">
    @forelse($shipments as $shipment)<tr><td class="p-4 font-semibold">{{ $shipment->tracking_number }}</td><td class="p-4">{{ $shipment->sellerOrder?->seller_order_number }}</td><td class="p-4">{{ $shipment->sellerOrder?->sellerProfile?->business_name }}</td><td class="p-4">{{ $shipment->sellerOrder?->order?->address?->formatted() }}</td><td class="p-4">{{ $shipment->serviceArea?->name ?? 'Unmatched' }}</td><td class="p-4 font-semibold">{{ str($shipment->current_status)->headline() }}</td><td class="p-4"><a class="text-primary" href="{{ route('logistics.parcels.show',$shipment) }}">View</a></td></tr>@empty<tr><td colspan="7" class="p-8 text-center text-muted">No parcel records.</td></tr>@endforelse
    </tbody></table></div>{{ $shipments->links() }}
</div>
@endsection
