@extends('Logistics.app')
@section('title','Parcel '.$shipment->tracking_number)
@section('content')
<div class="space-y-6">
    <header><a class="text-sm text-primary" href="{{ route('logistics.parcels') }}">← Back to Parcels</a><h1 class="mt-3 text-2xl font-bold text-ink">{{ $shipment->tracking_number }}</h1><p class="mt-1 text-sm font-semibold text-primary">{{ str($shipment->current_status)->headline() }}</p></header>
    <section class="grid gap-4 md:grid-cols-2"><article class="border border-line bg-surface p-5"><h2 class="font-semibold">Order and destination</h2><dl class="mt-4 space-y-2 text-sm"><div><dt class="text-muted">Order</dt><dd>{{ $shipment->sellerOrder?->seller_order_number }}</dd></div><div><dt class="text-muted">Seller</dt><dd>{{ $shipment->sellerOrder?->sellerProfile?->business_name }}</dd></div><div><dt class="text-muted">Buyer</dt><dd>{{ $shipment->sellerOrder?->order?->buyer?->name }}</dd></div><div><dt class="text-muted">Address</dt><dd>{{ $shipment->sellerOrder?->order?->address?->formatted() }}</dd></div><div><dt class="text-muted">Delivery area</dt><dd>{{ $shipment->serviceArea?->name ?? 'Not assigned' }}</dd></div></dl></article>
    <article class="border border-line bg-surface p-5"><h2 class="font-semibold">Items</h2><div class="mt-4 space-y-3">@foreach($shipment->sellerOrder?->items ?? [] as $item)<div class="flex justify-between gap-3 text-sm"><span>{{ $item->product_name }} <small class="text-muted">{{ $item->variant_description }}</small></span><strong>× {{ $item->quantity }}</strong></div>@endforeach</div></article></section>
    <section class="border border-line bg-surface p-5"><h2 class="font-semibold">Shipment history</h2><ol class="mt-4 space-y-3">@forelse($shipment->events as $event)<li class="border-l-2 border-primary pl-4"><strong class="text-sm">{{ str($event->status)->headline() }}</strong><p class="text-sm text-muted">{{ $event->notes }}</p><small class="text-muted">{{ $event->occurred_at?->format('M d, Y g:i A') }}</small></li>@empty<li class="text-sm text-muted">No events recorded.</li>@endforelse</ol></section>
</div>
@endsection
