<?php

return [
    'workspaces' => [
        'seller' => [
            'label' => 'Seller',
            'assistant_name' => 'LIKHAE Seller Assistant',
            'welcome' => 'Hi! I’m your LIKHAE Seller Assistant. I can help with products, orders, inventory, shop management, fulfillment, and Seller navigation.',
            'system_prompt' => 'You are the LIKHAE Seller AI Assistant. Help only an authenticated Seller use the Seller Center. Explain existing Seller pages, controls, statuses, and safe workflow steps for products, orders, inventory, sales, shop management, fulfillment, messages, reviews, marketing, reports, and account settings. Do not act on behalf of the user, invent live data, expose private records, or claim that you checked products, inventory, orders, buyers, payments, reports, or account records. Use only the supplied sanitized page context. If a question belongs to Buyer, Admin, Logistics, or Rider, say it is outside the Seller workspace and redirect the user to the appropriate workspace. Be concise, practical, and specific.',
            'shortcuts' => [
                ['icon' => '📦', 'label' => 'How do I update stock?'],
                ['icon' => '🧾', 'label' => 'How do I process an order?'],
                ['icon' => '🚚', 'label' => 'How do I hand over a parcel?'],
                ['icon' => '📈', 'label' => 'Where are my sales reports?'],
            ],
            'pages' => [
                'dashboard' => ['title' => 'Seller Dashboard', 'features' => ['review store performance', 'check orders needing action', 'monitor stock alerts', 'open Seller tools']],
                'products' => ['title' => 'Products', 'features' => ['create and edit products', 'manage product images', 'update stock', 'activate or archive listings']],
                'orders' => ['title' => 'Orders', 'features' => ['review Seller orders', 'update order status', 'prepare orders for pickup', 'open waybills']],
                'logistics' => ['title' => 'Seller Logistics', 'features' => ['review pickup readiness', 'hand over parcels', 'check waybills', 'follow shipment progress']],
                'messages' => ['title' => 'Messages', 'features' => ['read buyer conversations', 'send replies', 'contact support']],
                'reviews' => ['title' => 'Reviews', 'features' => ['read product reviews', 'reply to reviews', 'export review data']],
                'marketing' => ['title' => 'Marketing', 'features' => ['review campaigns', 'create vouchers', 'toggle campaign availability']],
                'reports' => ['title' => 'Reports', 'features' => ['review Seller performance', 'export reports', 'understand store metrics']],
                'store' => ['title' => 'Store Settings', 'features' => ['update store information', 'manage store details']],
                'account' => ['title' => 'Seller Account', 'features' => ['update profile', 'update business details', 'change password', 'manage notifications']],
                'notifications' => ['title' => 'Notifications', 'features' => ['review Seller alerts', 'mark notifications as read']],
            ],
            'local_answers' => [
                ['patterns' => ['add product', 'create product', 'edit product', 'update product', 'listing'], 'reply' => 'Open Products to create or edit a listing. Add the product details, images, price, variations, and stock, then save it for your store.'],
                ['patterns' => ['stock', 'inventory', 'quantity', 'out of stock'], 'reply' => 'Open Products and use the stock control for the listing you need to update. Keep the available quantity accurate so buyers do not order unavailable items.'],
                ['patterns' => ['order', 'orders', 'prepare'], 'reply' => 'Open Orders to review Seller orders and update each order through the next available fulfillment status. Use the order details and waybill when preparing a parcel.'],
                ['patterns' => ['pickup', 'handover', 'hand over', 'courier', 'waybill'], 'reply' => 'Open Seller Logistics to review pickup readiness and hand over a prepared parcel when the courier process is ready. Use the waybill to verify shipment details.'],
                ['patterns' => ['review', 'rating', 'feedback'], 'reply' => 'Open Reviews to read buyer feedback and reply to reviews. Keep replies specific, respectful, and focused on resolving the buyer’s concern.'],
                ['patterns' => ['marketing', 'campaign', 'voucher', 'discount'], 'reply' => 'Open Marketing to create or manage Seller campaigns and vouchers. Check the campaign details before making them available to buyers.'],
                ['patterns' => ['report', 'export', 'performance', 'sales'], 'reply' => 'Open Reports to review store performance and download Seller report data for the period you need.'],
            ],
        ],
        'rider' => [
            'label' => 'Rider',
            'assistant_name' => 'LIKHAE Rider Assistant',
            'welcome' => 'Hi! I’m your LIKHAE Rider Assistant. I can help with assigned deliveries, pickups, drop-offs, status updates, earnings, and Rider navigation.',
            'system_prompt' => 'You are the LIKHAE Rider AI Assistant. Help only an authenticated Rider use the Rider workspace. Explain existing Rider pages, controls, statuses, and safe workflow steps for assigned shipments, pickups, drop-offs, delivery status, earnings, history, messages, and account settings. Do not act on behalf of the user, invent live parcel or earnings data, expose customer information, or claim that you checked assignments, recipients, addresses, payments, commissions, or account records. Use only the supplied sanitized page context. If a question belongs to Buyer, Seller, Admin, or Logistics, say it is outside the Rider workspace and redirect the user to the appropriate workspace. Be concise, practical, and safety-conscious.',
            'shortcuts' => [
                ['icon' => '🛵', 'label' => 'How do I start a pickup?'],
                ['icon' => '📍', 'label' => 'How do I update delivery status?'],
                ['icon' => '💰', 'label' => 'Where can I see earnings?'],
                ['icon' => '🧾', 'label' => 'Where are my assignments?'],
            ],
            'pages' => [
                'dashboard' => ['title' => 'Rider Dashboard', 'features' => ['review today’s assignments', 'see pickup and delivery counts', 'open Rider tasks']],
                'shipments' => ['title' => 'Shipments', 'features' => ['review assigned shipments', 'open shipment details', 'update shipment status']],
                'parcels' => ['title' => 'Parcels', 'features' => ['review pickup parcels', 'open parcel details', 'confirm handoff steps']],
                'pickups' => ['title' => 'Pickups', 'features' => ['review pickup assignments', 'scan or confirm parcel pickup', 'update pickup status']],
                'deliveries' => ['title' => 'Deliveries', 'features' => ['review delivery assignments', 'update delivery status', 'record delivery outcomes']],
                'earnings' => ['title' => 'Earnings', 'features' => ['review earnings summaries', 'understand earning rows', 'review earnings history']],
                'history' => ['title' => 'Rider History', 'features' => ['review completed assignments', 'review past pickup and delivery activity']],
                'profile' => ['title' => 'Rider Profile', 'features' => ['update Rider profile', 'change password']],
                'messages' => ['title' => 'Messages', 'features' => ['contact Logistics', 'send delivery updates', 'read operational messages']],
            ],
            'local_answers' => [
                ['patterns' => ['assignment', 'shipment', 'task'], 'reply' => 'Open Shipments to review your assigned work and open a shipment for its current pickup or delivery step.'],
                ['patterns' => ['pickup', 'scan', 'handoff', 'handover'], 'reply' => 'Open Pickups, select the assigned parcel, and follow the scan or confirmation step shown for the pickup. Confirm only after checking the parcel and shipment details.'],
                ['patterns' => ['deliver', 'delivery', 'status', 'recipient', 'failed'], 'reply' => 'Open Deliveries to update the delivery status after the actual delivery attempt. Record a failed attempt only when the delivery could not be completed and the required details are available.'],
                ['patterns' => ['earning', 'pay', 'income', 'commission'], 'reply' => 'Open Earnings to review your earnings summary and the rows that contribute to the displayed total.'],
                ['patterns' => ['history', 'completed', 'past'], 'reply' => 'Open History to review completed pickup and delivery assignments from your Rider account.'],
                ['patterns' => ['message', 'contact', 'logistics'], 'reply' => 'Open Messages to communicate with Logistics about an assignment or delivery update.'],
                ['patterns' => ['profile', 'password', 'account'], 'reply' => 'Open your Rider Profile or Account area to update profile details and change your password.'],
            ],
        ],
        'logistics' => [
            'label' => 'Logistics',
            'assistant_name' => 'LIKHAE Logistics Assistant',
            'welcome' => 'Hi! I’m your LIKHAE Logistics Assistant. I can help with shipment monitoring, parcel intake, rider assignment, sorting, delivery management, and Logistics navigation.',
            'system_prompt' => 'You are the LIKHAE Logistics AI Assistant. Help only an authenticated Logistics user use the Logistics workspace. Explain existing Logistics pages, controls, statuses, and safe workflow steps for shipment monitoring, parcel intake, pickup requests, sorting, rider assignment, delivery management, riders, delivery areas, reports, messages, and account settings. Do not act on behalf of the user, invent live shipment or rider data, expose customer information, or claim that you checked parcels, recipients, addresses, riders, delivery areas, reports, or account records. Use only the supplied sanitized page context. If a question belongs to Buyer, Seller, Admin, or Rider, say it is outside the Logistics workspace and redirect the user to the appropriate workspace. Be concise, practical, and operationally clear.',
            'shortcuts' => [
                ['icon' => '📥', 'label' => 'How do I receive a parcel?'],
                ['icon' => '🛵', 'label' => 'How do I assign a rider?'],
                ['icon' => '🧭', 'label' => 'How do I sort a parcel?'],
                ['icon' => '📍', 'label' => 'How do I track a shipment?'],
            ],
            'pages' => [
                'dashboard' => ['title' => 'Logistics Dashboard', 'features' => ['review parcel flow', 'monitor pickups', 'monitor delivery assignments', 'open dispatch tools']],
                'parcels' => ['title' => 'Parcels', 'features' => ['review parcel status', 'receive parcels', 'open shipment details', 'view tracking']],
                'pickups' => ['title' => 'Pickup Requests', 'features' => ['review pickup requests', 'approve or reject pickups', 'assign pickups to riders']],
                'sorting' => ['title' => 'Sorting', 'features' => ['review parcels awaiting sorting', 'sort parcels by destination', 'update sorting status']],
                'assignments' => ['title' => 'Rider Assignments', 'features' => ['review unassigned parcels', 'assign riders', 'check rider workload']],
                'tracking' => ['title' => 'Tracking', 'features' => ['review shipment movement', 'check tracking events', 'open waybills']],
                'riders' => ['title' => 'Riders', 'features' => ['review Rider profiles', 'manage Rider applications', 'activate or deactivate riders']],
                'delivery-areas' => ['title' => 'Delivery Areas', 'features' => ['review service areas', 'manage delivery coverage', 'toggle delivery areas']],
                'messages' => ['title' => 'Messages', 'features' => ['contact riders', 'contact sellers', 'send Logistics updates']],
                'reports' => ['title' => 'Logistics Reports', 'features' => ['review delivery performance', 'export Logistics reports', 'understand parcel flow']],
                'profile' => ['title' => 'Logistics Profile', 'features' => ['update Logistics account details', 'change password']],
            ],
            'local_answers' => [
                ['patterns' => ['receive', 'scanner', 'scan', 'intake'], 'reply' => 'Open Parcels Receive to scan or confirm incoming parcels. Verify the shipment before confirming receipt so the parcel enters the correct Logistics flow.'],
                ['patterns' => ['pickup', 'approve', 'reject'], 'reply' => 'Open Pickup Requests to review a Seller pickup request, approve or reject it, and assign the parcel when the request is ready for dispatch.'],
                ['patterns' => ['sort', 'sorting', 'destination'], 'reply' => 'Open Sorting to review parcels awaiting sorting and update each parcel after it has been placed in the correct destination flow.'],
                ['patterns' => ['assign', 'rider', 'dispatch'], 'reply' => 'Open Rider Assignments to review unassigned parcels and select an available Rider. Check workload and destination before assigning.'],
                ['patterns' => ['track', 'tracking', 'waybill', 'shipment'], 'reply' => 'Open Parcels or Tracking to review verified shipment movement and open the waybill for the parcel’s tracking details.'],
                ['patterns' => ['application', 'activate', 'deactivate'], 'reply' => 'Open Riders to review Rider profiles and applications. Approve, activate, or deactivate riders only after checking the relevant account information.'],
                ['patterns' => ['area', 'coverage', 'delivery area'], 'reply' => 'Open Delivery Areas to review coverage and toggle the areas your Logistics center currently serves.'],
                ['patterns' => ['report', 'export', 'performance'], 'reply' => 'Open Reports to review Logistics performance and export the report for the selected period.'],
            ],
        ],
    ],
];
