@php $id=$id??request()->route('id')??'001234'; @endphp
<x-buyer.layout title="Order Details"><div class="b-page"><div class="b-container">
<x-buyer.breadcrumbs :items="[['label'=>'My Orders','url'=>route('buyer.orders')],['label'=>'Order #'.$id,'url'=>null]]" />
<div class="b-section-head"><div><h1 class="b-title">Order #LKH-2026-{{ $id }}</h1><p class="b-muted">Placed on August 29, 2026</p></div><x-buyer.status-badge type="warning">In Transit</x-buyer.status-badge></div>
<div class="b-order-detail-grid"><div>
<section class="b-card b-timeline">@foreach([['done','Order Placed','Aug 29 · 9:42 AM'],['done','Seller Preparing Order','Aug 29 · 2:10 PM'],['done','Shipped','Aug 30 · 10:20 AM'],['current','In Transit','Aug 30 · 5:30 PM'],['','Out for Delivery','Pending'],['','Delivered','Pending']] as [$state,$label,$time])<div class="b-timeline-item {{ $state }}"><div class="b-timeline-dot">{{ $state==='done'?'✓':'' }}</div><div><strong>{{ $label }}</strong><div class="b-muted" style="font-size:12px">{{ $time }}</div></div></div>@endforeach</section>
<section class="b-card" style="padding:20px;margin-top:16px"><h2 style="margin-top:0">Product</h2><div class="b-order-body"><div class="b-order-image"><img src="{{ asset('images/buyer/products/headphones.svg') }}" alt=""></div><div><strong>Premium Wireless Headphones</strong><div class="b-muted" style="font-size:12px">Black · Standard · Qty 1</div></div><strong>₱2,499.00</strong></div></section>
</div>
<aside><section class="b-card" style="padding:20px;margin-bottom:16px"><h2 style="margin-top:0;font-size:18px">Delivery</h2><div class="b-muted" style="font-size:12px">Courier</div><strong>LIKHAE Courier Partner</strong><div class="b-muted" style="font-size:12px;margin-top:12px">Tracking Number</div><strong>LKH-C-8294012</strong><div class="b-muted" style="font-size:12px;margin-top:12px">Shipping Address</div><strong>Brgy. San Isidro, Antipolo City, Rizal</strong></section>
<section class="b-card" style="padding:20px"><h2 style="margin-top:0;font-size:18px">Payment Summary</h2><div class="b-summary-row"><span>Subtotal</span><strong>₱2,499.00</strong></div><div class="b-summary-row"><span>Shipping</span><strong>₱60.00</strong></div><div class="b-summary-row"><span>Discount</span><strong>-₱200.00</strong></div><div class="b-summary-row b-summary-total"><span>Total</span><strong>₱2,359.00</strong></div><div style="display:grid;gap:8px;margin-top:15px"><a class="b-btn b-btn-secondary" href="{{ route('buyer.messages') }}">Message Seller</a><a class="b-btn b-btn-secondary" href="{{ route('buyer.messages') }}">Contact Support</a></div></section></aside></div>
</div></div></x-buyer.layout>
