@extends('layouts.seller')

@php $currentTab = $tab ?? request('tab', 'profile'); @endphp

@section('title', 'Account')
@section('active', 'account')
@section('subtitle', 'Manage your seller identity, business records, security, and preferences.')

@section('content')
<div class="sl-page">
    <div class="sl-page-toolbar"><div><span class="sl-eyebrow">Account Management</span><h2>Seller Account</h2><p>Keep your personal and business information secure and current.</p></div><span class="sl-account-status"><i></i> Account in good standing</span></div>
    <div class="sl-account-layout">
        <aside class="sl-card sl-account-nav">
            <div class="sl-account-person"><span class="sl-avatar">MS</span><div><strong>Mariel Santos</strong><small>Seller ID: SLR-20481</small></div></div>
            <nav>
                @foreach (['profile' => 'Profile', 'business' => 'Business Information', 'verification' => 'Verification', 'security' => 'Security', 'notifications' => 'Notification Settings'] as $key => $label)
                    <a href="{{ route('seller.account', ['tab' => $key]) }}" class="{{ $currentTab === $key ? 'is-active' : '' }}"><span>{{ $loop->iteration }}</span>{{ $label }}<i>›</i></a>
                @endforeach
            </nav>
        </aside>
        <main class="sl-account-content">
            @if ($currentTab === 'business')
                <form class="sl-card sl-form-section" data-demo-form data-success="Business information updated."><header class="sl-card-head"><div><h2>Business Information</h2><p>Legal information used for compliance and payouts.</p></div></header><div class="sl-form-grid"><label class="sl-field"><span>Registered business name</span><input value="LIKHAE Studio Trading"></label><label class="sl-field"><span>Business type</span><select><option>Sole Proprietorship</option><option>Partnership</option><option>Corporation</option></select></label><label class="sl-field"><span>DTI/SEC registration number</span><input value="DTI-2026-104829"></label><label class="sl-field"><span>TIN</span><input value="***-***-482-000"></label><label class="sl-field sl-span-2"><span>Registered business address</span><input value="24 Rizal Street, Santa Cruz, Laguna 4009"></label><label class="sl-field"><span>Authorized representative</span><input value="Mariel Santos"></label><label class="sl-field"><span>Business contact</span><input value="0917 000 2481"></label></div><div class="sl-form-actions"><button type="submit" class="sl-btn sl-btn-primary">Save Business Information</button></div></form>
            @elseif ($currentTab === 'verification')
                <section class="sl-card sl-verification-card"><header class="sl-card-head"><div><h2>Seller Verification</h2><p>Your documents help maintain a safe marketplace.</p></div><span class="sl-status is-success">Verified</span></header><div class="sl-verification-banner"><span>✓</span><div><strong>Your seller account is verified</strong><p>Verification completed on August 12, 2026. No action is currently required.</p></div></div><div class="sl-document-list">@foreach ([['Valid Government ID','Philippine Passport','Verified Aug 12, 2026'],['Business Permit','Santa Cruz Business Permit 2026','Verified Aug 12, 2026'],['DTI Registration','LIKHAE Studio Trading','Verified Aug 11, 2026']] as $doc)<article><span class="sl-file-icon">PDF</span><div><strong>{{ $doc[0] }}</strong><small>{{ $doc[1] }} · {{ $doc[2] }}</small></div><span class="sl-status is-success">Verified</span><button type="button" class="sl-btn sl-btn-ghost sl-btn-sm" data-demo-action="Document viewer opened.">View</button></article>@endforeach</div><div class="sl-help-card"><span>i</span><div><strong>Need to update a document?</strong><p>Contact Seller Support. Re-verification may temporarily limit selected account changes.</p></div><a href="{{ route('seller.messages') }}" class="sl-btn sl-btn-soft sl-btn-sm">Contact Support</a></div></section>
            @elseif ($currentTab === 'security')
                <section class="sl-card sl-form-section"><header class="sl-card-head"><div><h2>Security</h2><p>Protect access to your Seller Center.</p></div></header><div class="sl-security-score"><span><i style="width: 82%"></i></span><div><strong>Security score: Strong</strong><small>Enable all recommendations for maximum protection.</small></div></div><div class="sl-security-list"><article><span class="sl-security-icon">••</span><div><strong>Password</strong><p>Last changed 42 days ago</p></div><button type="button" class="sl-btn sl-btn-ghost sl-btn-sm" data-modal-open="passwordModal">Change</button></article><article><span class="sl-security-icon">2F</span><div><strong>Two-factor authentication</strong><p>Receive a code when signing in on a new device</p></div><label class="sl-switch"><input type="checkbox" checked><span></span></label></article><article><span class="sl-security-icon">DV</span><div><strong>Trusted devices</strong><p>3 devices currently have access</p></div><button type="button" class="sl-btn sl-btn-ghost sl-btn-sm" data-demo-action="Trusted devices opened.">Manage</button></article><article><span class="sl-security-icon">LG</span><div><strong>Login activity</strong><p>Last sign-in: Today, 8:42 AM · Santa Cruz, Laguna</p></div><button type="button" class="sl-btn sl-btn-ghost sl-btn-sm" data-demo-action="Login activity opened.">Review</button></article></div></section>
            @elseif ($currentTab === 'notifications')
                <form class="sl-card sl-form-section" data-demo-form data-success="Notification preferences saved."><header class="sl-card-head"><div><h2>Notification Settings</h2><p>Choose which Seller Center alerts you want to receive.</p></div></header><div class="sl-notification-settings"><div class="sl-notification-setting-head"><span>Notification Type</span><span>Email</span><span>Push</span><span>SMS</span></div>@foreach ([['New order','Receive an alert when a buyer places an order',true,true,true],['Order cancellation','Know when an order is cancelled',true,true,false],['Pickup and shipping','Courier assignment and shipment status changes',true,true,true],['Inventory alerts','Low-stock and out-of-stock reminders',true,true,false],['Buyer messages','New chat messages and support concerns',false,true,false],['Finance and payouts','Balance updates and payout confirmations',true,true,true],['Marketing updates','Campaign invitations and promotional tips',true,false,false]] as $setting)<div class="sl-notification-setting"><div><strong>{{ $setting[0] }}</strong><small>{{ $setting[1] }}</small></div>@foreach (array_slice($setting, 2) as $enabled)<label class="sl-check"><input type="checkbox" {{ $enabled ? 'checked' : '' }}><span>✓</span></label>@endforeach</div>@endforeach</div><div class="sl-form-actions"><button type="submit" class="sl-btn sl-btn-primary">Save Preferences</button></div></form>
            @else
                <form class="sl-card sl-form-section" data-demo-form data-success="Profile updated."><header class="sl-card-head"><div><h2>Profile Information</h2><p>Your private account identity and contact information.</p></div></header><div class="sl-profile-upload"><span class="sl-avatar">MS</span><div><strong>Profile photo</strong><p>JPG or PNG · maximum 2 MB</p><button type="button" class="sl-btn sl-btn-ghost sl-btn-sm" data-demo-action="Profile photo picker opened.">Change Photo</button></div></div><div class="sl-form-grid"><label class="sl-field"><span>First name</span><input value="Mariel" required></label><label class="sl-field"><span>Last name</span><input value="Santos" required></label><label class="sl-field"><span>Email address</span><input type="email" value="mariel@likhaestudio.ph" required></label><label class="sl-field"><span>Mobile number</span><input value="0917 000 2481" required></label><label class="sl-field"><span>Role</span><input value="Store Owner" disabled></label><label class="sl-field"><span>Seller ID</span><input value="SLR-20481" disabled></label></div><div class="sl-form-actions"><button type="submit" class="sl-btn sl-btn-primary">Save Profile</button></div></form>
            @endif
        </main>
    </div>
</div>

<div class="sl-modal" data-modal="passwordModal" hidden><div class="sl-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="passwordTitle"><header><div><span class="sl-eyebrow">Account Security</span><h2 id="passwordTitle">Change Password</h2></div><button type="button" class="sl-icon-btn" data-modal-close aria-label="Close">×</button></header><form data-demo-form data-success="Password changed successfully."><div class="sl-form-grid"><label class="sl-field sl-span-2"><span>Current password</span><input type="password" required></label><label class="sl-field sl-span-2"><span>New password</span><input type="password" minlength="8" required></label><label class="sl-field sl-span-2"><span>Confirm new password</span><input type="password" minlength="8" required></label></div><footer><button type="button" class="sl-btn sl-btn-ghost" data-modal-close>Cancel</button><button type="submit" class="sl-btn sl-btn-primary">Update Password</button></footer></form></div></div>
@endsection
