<?php

namespace App\Support;

class MarketplaceData
{
    /**
     * Get all 12 curated products in the mock marketplace catalog.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            [
                'id' => 1,
                'slug' => 'linen-lounge-set',
                'name' => 'Linen Lounge Set',
                'maker' => 'Wear Sundays',
                'location' => 'Cebu City',
                'category' => 'Wear',
                'subcategory' => 'Tops & Blouses',
                'price' => 1890,
                'compareAt' => 2290,
                'rating' => 4.8,
                'reviews' => 128,
                'sold' => 245,
                'badge' => 'LOCAL MAKER',
                'stock' => 4,
                'hasSizes' => true,
                'hasColors' => true,
                'colors' => [
                    ['name' => 'Terracotta', 'hex' => '#b45f44', 'stock' => 4, 'active' => true],
                    ['name' => 'Sand', 'hex' => '#c8b79a', 'stock' => 8, 'active' => false],
                    ['name' => 'Forest', 'hex' => '#415b46', 'stock' => 2, 'active' => false],
                    ['name' => 'Black', 'hex' => '#171717', 'stock' => 0, 'active' => false, 'disabled' => true],
                ],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'disabledSizes' => ['XL'],
                'description' => 'Made from a breathable cotton-linen blend, this relaxed set balances structure and ease. Cut and finished in Cebu in small runs, it features a boxy top, adjustable elastic waist, deep pockets, and fabric chosen for tropical weather.',
                'material' => '55% French Linen, 45% Organic Cotton',
                'fit' => 'Relaxed / Easy fit',
                'origin' => 'Cebu City, Philippines',
                'care' => 'Hand wash cold or gentle cycle, line dry in shade',
                'image' => 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 2,
                'slug' => 'handwoven-market-tote',
                'name' => 'Handwoven Market Tote',
                'maker' => 'Habi Norte',
                'location' => 'Benguet',
                'category' => 'Wear',
                'subcategory' => 'Shoes & Accessories',
                'price' => 1450,
                'compareAt' => null,
                'rating' => 4.9,
                'reviews' => 86,
                'sold' => 140,
                'badge' => 'NEW',
                'stock' => 12,
                'hasSizes' => false,
                'hasColors' => true,
                'colors' => [
                    ['name' => 'Natural Inabel', 'hex' => '#dfd7ca', 'stock' => 6, 'active' => true],
                    ['name' => 'Terracotta Stripe', 'hex' => '#b45f44', 'stock' => 4, 'active' => false],
                    ['name' => 'Indigo Weave', 'hex' => '#2b3a4a', 'stock' => 2, 'active' => false],
                ],
                'description' => 'A structured everyday tote woven on traditional wooden upright looms in the Cordilleras. Durable cotton warp with vegetable-dyed weft threads and reinforced full-grain leather handles.',
                'material' => '100% Upcycled Cotton Weave & Vegetable-Tanned Leather',
                'fit' => 'Generous tote (14" x 16" x 5")',
                'origin' => 'La Trinidad, Benguet',
                'care' => 'Spot clean with mild soap and damp cloth',
                'image' => 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 3,
                'slug' => 'sienna-stoneware-mug',
                'name' => 'Sienna Stoneware Mug',
                'maker' => 'Clay Story',
                'location' => 'Quezon City',
                'category' => 'Live',
                'subcategory' => 'Objects',
                'price' => 680,
                'compareAt' => null,
                'rating' => 4.7,
                'reviews' => 54,
                'sold' => 310,
                'badge' => null,
                'stock' => 15,
                'hasSizes' => false,
                'hasColors' => false,
                'description' => 'Hand-thrown on a potter wheel using local Laguna clay and dipped in a matte sienna reactive glaze. Each mug retains subtle fingertip marks from the artisan studio in Quezon City.',
                'material' => 'High-fire Stoneware Ceramic with Food-safe Matte Glaze',
                'fit' => '320ml capacity',
                'origin' => 'Quezon City, Philippines',
                'care' => 'Dishwasher and microwave safe. Hand wash recommended.',
                'image' => 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 4,
                'slug' => 'forest-home-diffuser',
                'name' => 'Forest Home Diffuser',
                'maker' => 'Amihan Studio',
                'location' => 'Davao City',
                'category' => 'Live',
                'subcategory' => 'Fragrance',
                'price' => 920,
                'compareAt' => null,
                'rating' => 4.9,
                'reviews' => 204,
                'sold' => 520,
                'badge' => 'BEST LOVED',
                'stock' => 2,
                'hasSizes' => false,
                'hasColors' => false,
                'description' => 'An earthy botanical diffuser distilled from native Benguet pine needles, Davao vetiver, and sweet calamansi rind. Formulated without synthetic phthalates for a long-lasting, calming room aroma.',
                'material' => 'Plant-based reed oil base with natural rattan reeds',
                'fit' => '150ml (lasts 3–4 months)',
                'origin' => 'Davao City, Philippines',
                'care' => 'Flip reeds every 7–10 days for optimal scent dispersion',
                'image' => 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 5,
                'slug' => 'marikina-leather-bag',
                'name' => 'Marikina Leather Day Bag',
                'maker' => 'Tahi Atelier',
                'location' => 'Marikina',
                'category' => 'Wear',
                'subcategory' => 'Shoes & Accessories',
                'price' => 3490,
                'compareAt' => 3990,
                'rating' => 4.8,
                'reviews' => 73,
                'sold' => 88,
                'badge' => 'LIMITED',
                'stock' => 5,
                'hasSizes' => false,
                'hasColors' => true,
                'colors' => [
                    ['name' => 'Cognac Tan', 'hex' => '#935128', 'stock' => 3, 'active' => true],
                    ['name' => 'Midnight Black', 'hex' => '#1a1a1a', 'stock' => 2, 'active' => false],
                    ['name' => 'Olive Moss', 'hex' => '#4e563d', 'stock' => 0, 'active' => false, 'disabled' => true],
                ],
                'description' => 'Crafted by master cordwainers in Marikina City using locally sourced vegetable-tanned cowhide. Features unlined natural suede interior, solid brass Japanese hardware, and an adjustable shoulder strap.',
                'material' => 'Full-Grain Vegetable-Tanned Leather & Solid Brass Hardware',
                'fit' => 'Compact daily shoulder carry (10" x 7" x 3")',
                'origin' => 'Marikina City, Philippines',
                'care' => 'Condition with natural beeswax leather balm every 6 months',
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 6,
                'slug' => 'mountain-roast',
                'name' => 'Mountain Roast Coffee Beans',
                'maker' => 'Cordillera Coffee Co.',
                'location' => 'Baguio',
                'category' => 'Taste',
                'subcategory' => 'Pantry',
                'price' => 540,
                'compareAt' => null,
                'rating' => 4.9,
                'reviews' => 318,
                'sold' => 840,
                'badge' => 'BEST LOVED',
                'stock' => 20,
                'hasSizes' => false,
                'hasColors' => false,
                'description' => 'Single-origin Arabica harvested at 1,500m elevation in Atok, Benguet. Medium roast profile with tasting notes of wild honey, cacao nibs, and toasted cedar.',
                'material' => '100% Single-Origin Typica Arabica Whole Beans',
                'fit' => '250g resealable valve pouch',
                'origin' => 'Atok, Benguet, Philippines',
                'care' => 'Store in a cool, airtight pantry away from direct sunlight',
                'image' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 7,
                'slug' => 'hand-carved-acacia-tray',
                'name' => 'Hand-Carved Acacia Wood Tray',
                'maker' => 'Pahiyas Woodcraft',
                'location' => 'Laguna',
                'category' => 'Live',
                'subcategory' => 'Tableware',
                'price' => 1120,
                'compareAt' => null,
                'rating' => 4.8,
                'reviews' => 42,
                'sold' => 115,
                'badge' => 'LOCAL MAKER',
                'stock' => 8,
                'hasSizes' => false,
                'hasColors' => false,
                'description' => 'Carved from sustainably pruned acacia trees in Paete, Laguna. Hand-rubbed with food-grade virgin coconut oil to showcase the organic contrast between sapwood and heartwood.',
                'material' => 'Solid Reclaimed Acacia Hardwood',
                'fit' => '14" x 8" organic oblong silhouette',
                'origin' => 'Paete, Laguna, Philippines',
                'care' => 'Wipe clean with a damp cloth; reapply coconut oil periodically',
                'image' => 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 8,
                'slug' => 'woven-rattan-coaster-set',
                'name' => 'Woven Rattan Coaster Set',
                'maker' => 'Isla Living',
                'location' => 'Bohol',
                'category' => 'Live',
                'subcategory' => 'Tableware',
                'price' => 480,
                'compareAt' => null,
                'rating' => 4.6,
                'reviews' => 39,
                'sold' => 210,
                'badge' => null,
                'stock' => 18,
                'hasSizes' => false,
                'hasColors' => false,
                'description' => 'A set of 6 tightly woven round coasters made from natural mountain rattan and nito vine accents. Handcrafted by weavers in Antequera, Bohol.',
                'material' => '100% Wild Rattan Core & Nito Vine',
                'fit' => 'Set of 6 (4" diameter with storage caddy)',
                'origin' => 'Antequera, Bohol, Philippines',
                'care' => 'Air dry thoroughly if wet; brush off crumbs with a dry cloth',
                'image' => 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 9,
                'slug' => 'south-sea-pearl-pendant',
                'name' => 'South Sea Pearl Artisan Pendant',
                'maker' => 'Luzon Goldsmiths',
                'location' => 'Manila',
                'category' => 'Wear',
                'subcategory' => 'Shoes & Accessories',
                'price' => 4200,
                'compareAt' => 4800,
                'rating' => 4.9,
                'reviews' => 61,
                'sold' => 74,
                'badge' => 'LIMITED',
                'stock' => 3,
                'hasSizes' => false,
                'hasColors' => false,
                'description' => 'A lustrous Palawan golden South Sea pearl set into an organic recycled 18k gold-vermeil bezel. Hand-forged in the historic jewelry quarter of Meycauayan / Manila.',
                'material' => 'Natural Golden South Sea Pearl (9–10mm) & 18k Gold-Plated Sterling Silver',
                'fit' => '18" adjustable cable chain with lobster clasp',
                'origin' => 'Manila / Palawan, Philippines',
                'care' => 'Avoid perfume and chemicals; polish with soft microfibre cloth',
                'image' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 10,
                'slug' => 'sun-drenched-activewear-set',
                'name' => 'Sun-Drenched Activewear Set',
                'maker' => 'Araw Movement',
                'location' => 'Siargao',
                'category' => 'Move',
                'subcategory' => 'Activewear & Yoga Pants',
                'price' => 2190,
                'compareAt' => null,
                'rating' => 4.8,
                'reviews' => 97,
                'sold' => 180,
                'badge' => 'NEW',
                'stock' => 9,
                'hasSizes' => true,
                'hasColors' => true,
                'colors' => [
                    ['name' => 'Clay Sage', 'hex' => '#7b8a78', 'stock' => 5, 'active' => true],
                    ['name' => 'Sunset Ochre', 'hex' => '#c98a4b', 'stock' => 4, 'active' => false],
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'disabledSizes' => [],
                'description' => 'A four-way stretch bra and high-waist legging set crafted from recycled ocean nylon. Moisture-wicking and quick-drying, tailored for tropical surf, yoga, and movement sessions.',
                'material' => '78% Recycled Econyl Nylon, 22% Elastane',
                'fit' => 'High-support compression fit',
                'origin' => 'Siargao Island, Philippines',
                'care' => 'Machine wash cold inside-out; do not tumble dry',
                'image' => 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 11,
                'slug' => 'hablon-heritage-midi-dress',
                'name' => 'Hablon Heritage Midi Dress',
                'maker' => 'Iloilo Loom',
                'location' => 'Iloilo City',
                'category' => 'Wear',
                'subcategory' => 'Dresses & Skirts',
                'price' => 2850,
                'compareAt' => 3400,
                'rating' => 4.9,
                'reviews' => 52,
                'sold' => 95,
                'badge' => 'LOCAL MAKER',
                'stock' => 3,
                'hasSizes' => true,
                'hasColors' => true,
                'colors' => [
                    ['name' => 'Rose Hablon', 'hex' => '#c27d82', 'stock' => 3, 'active' => true],
                    ['name' => 'Natural Raw', 'hex' => '#ded4c5', 'stock' => 0, 'active' => false, 'disabled' => true],
                ],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'disabledSizes' => ['XL'],
                'description' => 'A flowing tier-skirt midi dress cut from handloom Hablon cotton from Miag-ao, Iloilo. Features delicate shell buttons down the front, relaxed bishop sleeves, and deep side pockets.',
                'material' => '100% Handwoven Miag-ao Hablon Cotton',
                'fit' => 'Relaxed A-line midi length (44" length)',
                'origin' => 'Miag-ao, Iloilo, Philippines',
                'care' => 'Gentle hand wash with mild detergent; steam or iron on cotton setting',
                'image' => 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
            [
                'id' => 12,
                'slug' => 'botanical-glow-facial-elixir',
                'name' => 'Botanical Glow Facial Elixir',
                'maker' => 'Diwa Botanicals',
                'location' => 'Palawan',
                'category' => 'Glow',
                'subcategory' => 'Skincare',
                'price' => 1180,
                'compareAt' => null,
                'rating' => 4.9,
                'reviews' => 412,
                'sold' => 960,
                'badge' => 'BEST LOVED',
                'stock' => 14,
                'hasSizes' => false,
                'hasColors' => false,
                'description' => 'A golden cold-pressed face oil combining wild Palawan Elemi resin, pili nut squalane, moringa seed oil, and botanical vitamin C for luminous, deeply nourished skin.',
                'material' => '100% Wild-Harvested Elemi, Pili Squalane, Moringa & Rosehip Oil',
                'fit' => '30ml amber glass dropper bottle',
                'origin' => 'Puerto Princesa, Palawan, Philippines',
                'care' => 'Apply 3–4 drops morning and night on damp skin. Keep out of direct sun.',
                'image' => 'https://images.unsplash.com/photo-1608248597359-25f0a8274737?auto=format&fit=crop&w=900&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1608248597359-25f0a8274737?auto=format&fit=crop&w=1200&q=88',
                    'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=88',
                ],
            ],
        ];
    }

    /**
     * Find a product by its URL slug.
     */
    public static function findBySlug(string $slug): ?array
    {
        return collect(self::all())->firstWhere('slug', $slug) ?? self::all()[0];
    }
}

