@extends('Seller.layouts.auth')
@section('title', 'Seller Registration — LIKHAE')

@section('content')
@php $step = (int) request('step', 1); @endphp
<section class="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:py-14">
    <div class="mb-8">
        <p class="page-eyebrow">SELLER APPLICATION</p>
        <h1 class="mt-2 text-3xl font-black tracking-[-.04em]">Become a LIKHAE Seller</h1>
        <p class="mt-2 text-sm text-[#6B6864]">Complete your business application. You can review everything before submission.</p>
    </div>
    <div class="registration-steps">
        @foreach(['Personal','Address','Business','Documents','Security','Review'] as $i => $label)
            <div class="registration-step {{ $step >= $i + 1 ? 'is-active' : '' }}"><span>{{ $i + 1 }}</span><small>{{ $label }}</small></div>
        @endforeach
    </div>
    <form class="auth-card mt-6 max-w-none" method="POST" action="{{ url('/seller/register') }}" enctype="multipart/form-data">
        @csrf
        <input type="hidden" name="step" value="{{ $step }}">
        @if($step === 1)
            <div class="form-section-title"><span>01</span><div><h2>Personal Information</h2><p>Tell us who will own and manage this seller account.</p></div></div><div class="form-grid"><div><label class="form-label">Last Name *</label><input class="form-input" name="last_name" required></div><div><label class="form-label">First Name *</label><input class="form-input" name="first_name" required></div><div><label class="form-label">Middle Initial</label><input class="form-input" name="middle_initial" maxlength="2"></div><div><label class="form-label">Sex *</label><select class="form-input" name="sex" required><option value="">Select</option><option>Female</option><option>Male</option><option>Prefer not to say</option></select></div><div><label class="form-label">Email *</label><input class="form-input" name="email" type="email" required></div><div><label class="form-label">Contact Number *</label><input class="form-input" name="contact" placeholder="+63 9XX XXX XXXX" required></div><div><label class="form-label">Birthday *</label><input id="birthday" class="form-input" name="birthday" type="date" required></div><div><label class="form-label">Age</label><input id="age" class="form-input bg-[#F6F4F0]" readonly placeholder="Auto-generated"></div></div>
        @elseif($step === 2)
            <div class="form-section-title"><span>02</span><div><h2>Address</h2><p>Use the Philippine address hierarchy for accurate pickup and verification.</p></div></div><div class="form-grid"><div><label class="form-label">Province *</label><select class="form-input" name="province" required><option>Cebu</option><option>Metro Manila</option><option>Benguet</option><option>Davao del Sur</option></select></div><div><label class="form-label">Municipality / City *</label><select class="form-input" name="city" required><option>Cebu City</option></select></div><div><label class="form-label">Barangay *</label><select class="form-input" name="barangay" required><option>Lahug</option></select></div><div><label class="form-label">Postal Code</label><input class="form-input" name="postal_code" value="6000"></div><div><label class="form-label">House / Unit *</label><input class="form-input" name="house" required></div><div><label class="form-label">Street / Subdivision *</label><input class="form-input" name="street" required></div><div class="sm:col-span-2"><label class="form-label">Landmark / Additional Details</label><textarea class="form-input min-h-24" name="landmark"></textarea></div></div>
        @elseif($step === 3)
            <div class="form-section-title"><span>03</span><div><h2>Business Information</h2><p>Information customers and LIKHAE use to identify your shop.</p></div></div><div class="form-grid"><div><label class="form-label">Business Name *</label><input class="form-input" name="business_name" required></div><div><label class="form-label">Store Name *</label><input class="form-input" name="store_name" placeholder="Maria’s Local Finds" required></div><div><label class="form-label">Line of Business *</label><select class="form-input" name="category" required><option>Local Products</option><option>Fashion</option><option>Food & Beverage</option><option>Home & Living</option><option>Electronics</option></select></div><div><label class="form-label">Business Type *</label><select class="form-input" name="business_type" required><option>Individual Seller</option><option>Sole Proprietorship</option><option>Partnership</option><option>Corporation</option></select></div><div><label class="form-label">DTI / SEC Number</label><input class="form-input" name="registration_number"></div><div><label class="form-label">TIN</label><input class="form-input" name="tin"></div></div>
        @elseif($step === 4)
            <div class="form-section-title"><span>04</span><div><h2>Verification Documents</h2><p>Upload clear and valid documents for seller verification.</p></div></div><div class="grid gap-4 sm:grid-cols-2"><label class="upload-card"><svg viewBox="0 0 24 24"><path d="M12 16V4m0 0-4 4m4-4 4 4"/><path d="M4 15v5h16v-5"/></svg><strong>Government ID *</strong><span>JPG, PNG or PDF · Max 5MB</span><input type="file" name="government_id" hidden required></label><label class="upload-card"><svg viewBox="0 0 24 24"><path d="M12 16V4m0 0-4 4m4-4 4 4"/><path d="M4 15v5h16v-5"/></svg><strong>Business Permit *</strong><span>JPG, PNG or PDF · Max 5MB</span><input type="file" name="business_permit" hidden required></label></div>
        @elseif($step === 5)
            <div class="form-section-title"><span>05</span><div><h2>Account Security</h2><p>Create a secure password for your seller account.</p></div></div><div class="max-w-xl space-y-4"><div><label class="form-label">Password *</label><input id="password" class="form-input" type="password" name="password" required></div><div><label class="form-label">Confirm Password *</label><input class="form-input" type="password" name="password_confirmation" required></div><div class="border border-[#E5E0D9] bg-[#F6F4F0] p-4 text-xs leading-6 text-[#6B6864]">Use at least 8 characters with uppercase, lowercase, and a number.</div><label class="flex items-start gap-3 text-xs leading-5 text-[#6B6864]"><input class="mt-1 accent-[#D92D2F]" type="checkbox" required><span>I agree to the LIKHAE Seller Terms, Marketplace Policies, and Privacy Policy.</span></label></div>
        @else
            <div class="form-section-title"><span>06</span><div><h2>Review & Submit</h2><p>Check your details before sending your application for review.</p></div></div><div class="grid gap-4 sm:grid-cols-2"><div class="review-block"><span>PERSONAL</span><strong>Maria Santos</strong><p>maria@example.com · +63 917 123 4567</p></div><div class="review-block"><span>ADDRESS</span><strong>Cebu City, Cebu</strong><p>Lahug · 6000</p></div><div class="review-block"><span>BUSINESS</span><strong>Maria’s Local Finds</strong><p>Local Products · Individual Seller</p></div><div class="review-block"><span>DOCUMENTS</span><strong>2 files ready</strong><p>Government ID · Business Permit</p></div></div>
        @endif
        <div class="mt-8 flex flex-wrap justify-between gap-3 border-t border-[#E5E0D9] pt-5">@if($step > 1)<a class="btn-secondary" href="{{ url('/seller/register?step=' . ($step - 1)) }}">Back</a>@else<span></span>@endif @if($step < 6)<a class="btn-primary" href="{{ url('/seller/register?step=' . ($step + 1)) }}">Continue</a>@else<button class="btn-primary" type="submit">Submit Application</button>@endif</div>
    </form>
</section>
<script>document.getElementById('birthday')?.addEventListener('change', function () { const birthday = new Date(this.value); const today = new Date(); let age = today.getFullYear() - birthday.getFullYear(); const month = today.getMonth() - birthday.getMonth(); if (month < 0 || (month === 0 && today.getDate() < birthday.getDate())) age--; document.getElementById('age').value = Number.isFinite(age) ? age : ''; });</script>
@endsection
