
<x-buyer.layout title="Home">
<div class="b-page"><div class="b-container">
<section class="b-card b-hero b-shadow"><div class="b-hero-copy"><span class="b-eyebrow">Welcome to LIKHAE</span><h1>Everything you need, all in one place.</h1><p>Discover quality products from trusted sellers across every category. Shop confidently with secure checkout, buyer protection, easy order tracking, and direct seller messaging.</p><div class="b-hero-actions"><a class="b-btn b-btn-primary" href="{{ route('buyer.products') }}">Shop Now</a><a class="b-btn b-btn-secondary" href="#buyerCategories">Explore Categories</a></div></div><div class="b-hero-products">@foreach(array_slice($buyerProducts,0,4) as $product)<a class="b-hero-product" href="{{ route('buyer.product-details',$product['slug']) }}"><img src="{{ asset(ltrim($product['image'],'/')) }}" alt="{{ $product['name'] }}"></a>@endforeach</div></section>
<section class="b-benefits"><div class="b-benefit"><span class="b-benefit-icon">🚚</span><div><strong>Free Shipping</strong><small>On selected orders</small></div></div><div class="b-benefit"><span class="b-benefit-icon">🔒</span><div><strong>Secure Payments</strong><small>Protected checkout</small></div></div><div class="b-benefit"><span class="b-benefit-icon">↩</span><div><strong>Easy Returns</strong><small>Simple return support</small></div></div><div class="b-benefit"><span class="b-benefit-icon">✓</span><div><strong>Buyer Protection</strong><small>Support throughout your order</small></div></div></section>
<section class="b-section" id="buyerCategories"><div class="b-section-head"><div><h2 class="b-section-title">Shop by Category</h2><p class="b-muted">Explore popular categories across LIKHAE.</p></div><a class="b-section-link" href="{{ route('buyer.products') }}">View all →</a></div>@php $categories=[['Fashion','/images/buyer/categories/fashion.svg'],['Electronics','/images/buyer/categories/electronics.svg'],['Home & Living','/images/buyer/categories/home.svg'],['Beauty & Health','/images/buyer/categories/beauty.svg'],['Sports & Outdoors','/images/buyer/categories/sports.svg'],['Toys & Games','/images/buyer/categories/toys.svg'],['Automotive','/images/buyer/categories/automotive.svg'],['Books & Stationery','/images/buyer/categories/books.svg']]; @endphp<div class="b-category-grid">@foreach($categories as [$category,$image])<a class="b-category-card" href="{{ route('buyer.products',['category'=>$category]) }}"><img src="{{ asset(ltrim($image,'/')) }}" alt=""><strong>{{ $category }}</strong></a>@endforeach</div></section>
<section class="b-section"><div class="b-card b-deal-banner"><div><small>FLASH DEALS</small><h2 style="margin:5px 0 0">Limited-time marketplace prices</h2></div><div class="b-countdown"><span>06h</span><span>24m</span><span>18s</span></div></div><div class="b-product-grid" style="margin-top:14px">@foreach(array_slice($buyerProducts,0,4) as $product)<x-buyer.product-card :product="$product" />@endforeach</div></section>
@foreach([['Featured Products',array_slice($buyerProducts,4,4)],['Best Sellers',array_slice($buyerProducts,2,4)],['Recommended for You',array_slice($buyerProducts,6,4)]] as [$title,$products])<section class="b-section"><div class="b-section-head"><div><h2 class="b-section-title">{{ $title }}</h2><p class="b-muted">Curated marketplace picks from trusted sellers.</p></div></div><div class="b-product-grid">@foreach($products as $product)<x-buyer.product-card :product="$product" />@endforeach</div></section>@endforeach
</div></div>
</x-buyer.layout>
