@php
$buyerProducts=[
['id'=>'wireless-headphones','slug'=>'wireless-headphones','name'=>'Premium Wireless Headphones','category'=>'Electronics','seller'=>'Metro Finds PH','location'=>'Makati City','price'=>2499,'old_price'=>2999,'discount'=>17,'rating'=>4.8,'reviews'=>128,'sold'=>250,'stock'=>18,'image'=>'/images/buyer/products/headphones.svg'],
['id'=>'classic-backpack','slug'=>'classic-backpack','name'=>'Classic Everyday Backpack','category'=>'Bags','seller'=>'Urban Carry Co.','location'=>'Quezon City','price'=>999,'old_price'=>1299,'discount'=>23,'rating'=>4.7,'reviews'=>92,'sold'=>410,'stock'=>26,'image'=>'/images/buyer/products/backpack.svg'],
['id'=>'running-shoes','slug'=>'running-shoes','name'=>'Lightweight Running Shoes','category'=>'Sports & Outdoors','seller'=>'Stride PH','location'=>'Pasig City','price'=>1799,'old_price'=>2199,'discount'=>18,'rating'=>4.9,'reviews'=>205,'sold'=>540,'stock'=>14,'image'=>'/images/buyer/products/shoes.svg'],
['id'=>'smart-watch','slug'=>'smart-watch','name'=>'Everyday Smart Watch','category'=>'Electronics','seller'=>'Tech Avenue','location'=>'Taguig City','price'=>2190,'old_price'=>2690,'discount'=>19,'rating'=>4.7,'reviews'=>164,'sold'=>325,'stock'=>20,'image'=>'/images/buyer/products/watch.svg'],
['id'=>'skincare-set','slug'=>'skincare-set','name'=>'Daily Skincare Essentials Set','category'=>'Beauty & Health','seller'=>'Glow Market','location'=>'Manila','price'=>899,'old_price'=>1099,'discount'=>18,'rating'=>4.8,'reviews'=>110,'sold'=>290,'stock'=>31,'image'=>'/images/buyer/products/skincare.svg'],
['id'=>'mechanical-keyboard','slug'=>'mechanical-keyboard','name'=>'Compact Mechanical Keyboard','category'=>'Electronics','seller'=>'KeyHub PH','location'=>'Mandaluyong City','price'=>1899,'old_price'=>2299,'discount'=>17,'rating'=>4.9,'reviews'=>180,'sold'=>460,'stock'=>17,'image'=>'/images/buyer/products/keyboard.svg'],
['id'=>'coffee-maker','slug'=>'coffee-maker','name'=>'Compact Home Coffee Maker','category'=>'Home & Living','seller'=>'Kitchen+ Manila','location'=>'Manila','price'=>1599,'old_price'=>1899,'discount'=>16,'rating'=>4.6,'reviews'=>84,'sold'=>170,'stock'=>11,'image'=>'/images/buyer/products/coffee.svg'],
['id'=>'desk-lamp','slug'=>'desk-lamp','name'=>'Minimal Adjustable Desk Lamp','category'=>'Home & Living','seller'=>'Home Basics MNL','location'=>'Marikina City','price'=>749,'old_price'=>899,'discount'=>17,'rating'=>4.6,'reviews'=>71,'sold'=>180,'stock'=>22,'image'=>'/images/buyer/products/lamp.svg'],
['id'=>'basketball','slug'=>'basketball','name'=>'Indoor / Outdoor Basketball','category'=>'Sports & Outdoors','seller'=>'Playground PH','location'=>'Cavite','price'=>699,'old_price'=>849,'discount'=>18,'rating'=>4.7,'reviews'=>89,'sold'=>201,'stock'=>34,'image'=>'/images/buyer/products/basketball.svg'],
['id'=>'book-set','slug'=>'book-set','name'=>'Modern Reading Essentials Set','category'=>'Books & Stationery','seller'=>'Paper Trail PH','location'=>'Laguna','price'=>559,'old_price'=>699,'discount'=>20,'rating'=>4.8,'reviews'=>74,'sold'=>150,'stock'=>42,'image'=>'/images/buyer/products/book.svg'],
['id'=>'pet-supplies','slug'=>'pet-supplies','name'=>'Everyday Pet Care Starter Set','category'=>'Pet Supplies','seller'=>'Happy Paws PH','location'=>'Quezon City','price'=>799,'old_price'=>949,'discount'=>16,'rating'=>4.9,'reviews'=>98,'sold'=>220,'stock'=>28,'image'=>'/images/buyer/products/pet.svg'],
];
@endphp
