@extends('Logistics.app')
@section('title','Logistics Account - LIKHAE')
@section('content')
<div class="space-y-6"><header><p class="text-xs font-bold uppercase text-primary">Account Management</p><h1 class="mt-2 text-2xl font-bold">{{ $center->business_name }}</h1><p class="mt-2 text-sm text-muted">Approved logistics center and owner account information.</p></header>
	@if(session('status'))<div class="border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('status') }}</div>@endif
	@if($errors->any())<div class="border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
	<section class="grid gap-4 md:grid-cols-2">
		<form method="POST" action="{{ route('logistics.account.profile.update') }}" class="border border-line bg-surface p-5">@csrf @method('PATCH')<h2 class="font-semibold">Owner Account</h2><div class="mt-4 grid gap-3"><label class="grid gap-1 text-sm">First name<input class="border border-line px-3 py-2" name="first_name" value="{{ old('first_name', $user->first_name) }}" required></label><label class="grid gap-1 text-sm">Last name<input class="border border-line px-3 py-2" name="last_name" value="{{ old('last_name', $user->last_name) }}" required></label><label class="grid gap-1 text-sm">Email<input class="border border-line px-3 py-2" type="email" name="email" value="{{ old('email', $user->email) }}" required></label><label class="grid gap-1 text-sm">Contact number<input class="border border-line px-3 py-2" name="contact_number" value="{{ old('contact_number', $user->contact_number) }}" required></label><button class="bg-primary px-4 py-2 text-sm font-semibold text-white">Save Profile</button></div></form>
		<article class="border border-line bg-surface p-5"><h2 class="font-semibold">Center</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-muted">Code</dt><dd>{{ $center->code }}</dd></div><div><dt class="text-muted">Business</dt><dd>{{ $center->business_name }}</dd></div><div><dt class="text-muted">Address</dt><dd>{{ $center->address?->formatted() }}</dd></div><div><dt class="text-muted">Status</dt><dd>{{ str($center->status)->headline() }}</dd></div></dl></article>
	</section>
	<form method="POST" action="{{ route('logistics.account.password.update') }}" class="grid gap-3 border border-line bg-surface p-5 md:grid-cols-4">@csrf @method('PATCH')<h2 class="font-semibold md:col-span-4">Change Password</h2><input class="border border-line px-3 py-2" name="current_password" type="password" placeholder="Current password" required><input class="border border-line px-3 py-2" name="password" type="password" placeholder="New password" required><input class="border border-line px-3 py-2" name="password_confirmation" type="password" placeholder="Confirm password" required><button class="bg-primary px-4 py-2 text-sm font-semibold text-white">Update Password</button></form>
	<form method="POST" action="{{ route('logout') }}">@csrf<button class="border border-red-200 px-4 py-2 font-semibold text-red-700">Logout</button></form>
</div>
@endsection
