<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Waybill {{ $tracking }} | LIKHAE</title>
    @vite('resources/css/logistic/app.css')
    <style>@media print {.no-print { display: none !important; } body { background: #fff !important; } .waybill { box-shadow: none !important; border-color: #111 !important; }}</style>
</head>
<body class="bg-page p-4 text-ink sm:p-8">
@php $parcel = ['LH-2026-1001' => ['order' => 'ORD-2026-1045', 'recipient' => 'Juan Dela Cruz', 'contact' => '0917 123 4567', 'address' => '21 Rizal Street, Brgy. Bubukal, Santa Cruz, Laguna', 'payment' => 'Cash on Delivery'], 'LH-2026-1002' => ['order' => 'ORD-2026-1046', 'recipient' => 'Maria Santos', 'contact' => '0918 456 7712', 'address' => '18 Riverside Street, Brgy. Sampaloc, Pagsanjan, Laguna', 'payment' => 'GCash']][$tracking] ?? ['order' => 'ORD-2026-1047', 'recipient' => 'Ana Reyes', 'contact' => '0919 845 2201', 'address' => '15 Lopez Avenue, Brgy. Batong Malake, Los Baños, Laguna', 'payment' => 'GCash']; @endphp
<main class="waybill mx-auto max-w-2xl rounded-xl border-2 border-ink bg-surface p-6 shadow-sm sm:p-9"><div class="flex items-start justify-between gap-4 border-b-2 border-ink pb-5"><div><strong class="text-xl tracking-wide text-primary">LIKHAE</strong><p class="mt-1 text-xs text-muted">Marketplace Logistics Waybill</p></div><button class="no-print rounded-lg bg-primary px-4 py-2 text-xs font-bold text-white" onclick="window.print()">Print</button></div><div class="grid gap-6 py-6 sm:grid-cols-2"><section><span class="text-[10px] font-bold uppercase tracking-widest text-muted">Deliver to</span><h1 class="mt-2 text-lg font-bold">{{ $parcel['recipient'] }}</h1><p class="mt-2 text-sm leading-6">{{ $parcel['contact'] }}<br>{{ $parcel['address'] }}</p></section><section class="sm:text-right"><span class="text-[10px] font-bold uppercase tracking-widest text-muted">Tracking number</span><strong class="mt-2 block text-xl tracking-wider">{{ $tracking }}</strong><div class="mt-3 inline-block rounded border-2 border-ink px-3 py-2 font-mono text-lg tracking-[0.3em]">||| ||| ||||</div></section></div><div class="grid gap-3 border-t border-line pt-5 text-sm sm:grid-cols-3"><div><span class="block text-[10px] uppercase text-muted">Order</span><strong>{{ $parcel['order'] }}</strong></div><div><span class="block text-[10px] uppercase text-muted">Service</span><strong>Standard Delivery</strong></div><div><span class="block text-[10px] uppercase text-muted">Payment</span><strong>{{ $parcel['payment'] }}</strong></div></div><p class="mt-8 border-t border-line pt-4 text-[10px] text-muted">Scan the tracking number at each handoff. This frontend waybill is a printable template; parcel data requires the Logistics backend.</p></main>
</body>
</html>
