@extends('Rider.app')
@section('title','Rider Account - LIKHAE')
@section('content')
<div class="space-y-6"><header><p class="text-xs font-bold uppercase text-primary">Account Management</p><h1 class="mt-2 text-2xl font-bold">{{ $rider->user?->name }}</h1><p class="mt-2 text-sm text-muted">Your approved rider and vehicle information.</p></header>
	@if(session('status'))<div class="border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('status') }}</div>@endif
	@if($errors->any())<div class="border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
	<section class="grid gap-4 md:grid-cols-2">
		<form method="POST" action="{{ route('rider.account.profile.update') }}" class="border border-line bg-surface p-5">@csrf @method('PATCH')<h2 class="font-semibold">Personal Information</h2><div class="mt-4 grid gap-3"><label class="grid gap-1 text-sm">First name<input class="border border-line px-3 py-2" name="first_name" value="{{ old('first_name', $rider->user?->first_name) }}" required></label><label class="grid gap-1 text-sm">Last name<input class="border border-line px-3 py-2" name="last_name" value="{{ old('last_name', $rider->user?->last_name) }}" required></label><label class="grid gap-1 text-sm">Email<input class="border border-line px-3 py-2" type="email" name="email" value="{{ old('email', $rider->user?->email) }}" required></label><label class="grid gap-1 text-sm">Contact number<input class="border border-line px-3 py-2" name="contact_number" value="{{ old('contact_number', $rider->user?->contact_number) }}" required></label><p class="text-xs text-muted">Birthday: {{ $rider->user?->birthday?->format('M d, Y') }} · Status: {{ str($rider->status)->headline() }}</p><button class="bg-primary px-4 py-2 text-sm font-semibold text-white">Save Profile</button></div></form>
		<article class="border border-line bg-surface p-5"><h2 class="font-semibold">Vehicle and Coverage</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-muted">Vehicle</dt><dd>{{ str($rider->vehicle_type)->headline() }}</dd></div><div><dt class="text-muted">Plate</dt><dd>{{ $rider->plate_number }}</dd></div><div><dt class="text-muted">Logistics Center</dt><dd>{{ $rider->logisticsCenter?->business_name }}</dd></div><div><dt class="text-muted">Areas</dt><dd>{{ $rider->areaAssignments->where('is_active',true)->pluck('serviceArea.name')->filter()->join(', ') ?: 'No active area' }}</dd></div></dl></article>
	</section>
	<form method="POST" action="{{ route('rider.account.password.update') }}" class="grid gap-3 border border-line bg-surface p-5 md:grid-cols-4">@csrf @method('PATCH')<h2 class="font-semibold md:col-span-4">Change Password</h2><input class="border border-line px-3 py-2" name="current_password" type="password" placeholder="Current password" required><input class="border border-line px-3 py-2" name="password" type="password" placeholder="New password" required><input class="border border-line px-3 py-2" name="password_confirmation" type="password" placeholder="Confirm password" required><button class="bg-primary px-4 py-2 text-sm font-semibold text-white">Update Password</button></form>
	<form method="POST" action="{{ route('logout') }}">@csrf<button class="border border-red-200 px-4 py-2 font-semibold text-red-700">Logout</button></form>
</div>
@endsection
